# %%
# =====================================================================
# OpenSeesPy 3D Pushover Model  —  E2K Model
# Generated by E2K 3D Analyzer  on  2026-05-01
# Units: kN, m  (stresses in kPa = kN/m²)
# SDC: D    Frame system: special
# ─────────────────────────────────────────────────────────────────────
# Geometric transforms:
#   1 = Columns     vecxz = (1,0,0)  →  local_y = global X
#   2 = Y-beams     vecxz = (1,0,0)  →  local_y = global Z  (Wy = −w)
#   3 = X-beams     vecxz = (0,1,0)  →  local_y = global −Z (Wy = +w)
#   4 = Diagonal    vecxz = (0,0,1)  →  local_z = global Z  (Wz = −w)
# =====================================================================

import json
import os
import subprocess
import sys
import tempfile

_ADRS_WORKER_ENV = 'CE259_ADRS_WORKER'
_ADRS_DIRECTION_ENV = 'CE259_ADRS_DIRECTION'
_ADRS_OUTPUT_ENV = 'CE259_ADRS_OUTPUT'

_DIRECTION_CONFIGS = {
    'pos_x': {'label': '+X', 'axis': 'X', 'dof': 1, 'sign':  1.0, 'key': 'pos_x'},
    'neg_x': {'label': '-X', 'axis': 'X', 'dof': 1, 'sign': -1.0, 'key': 'neg_x'},
    'pos_y': {'label': '+Y', 'axis': 'Y', 'dof': 2, 'sign':  1.0, 'key': 'pos_y'},
    'neg_y': {'label': '-Y', 'axis': 'Y', 'dof': 2, 'sign': -1.0, 'key': 'neg_y'},
}
_DIRECTION_ORDER = ['pos_x', 'neg_x', 'pos_y', 'neg_y']


def _plot_direction_adrs(result):
    import matplotlib.pyplot as plt

    direction = result['direction']
    sd_hist = result['sd_hist']
    sa_hist = result['sa_hist']
    capacity_sd = result['capacity_sd']
    demand_sa = result['demand_sa']
    performance = result['performance_point']
    hazus = result['hazus']

    fig, ax = plt.subplots(figsize=(7.4, 5.4))

    thresholds = hazus['thresholds']
    xmax_candidates = [max(sd_hist or [0.0])]
    xmax_candidates.extend(thresholds.values())
    if performance is not None:
        xmax_candidates.append(performance['sd'])
    xmax = max(xmax_candidates) * 1.08 if max(xmax_candidates) > 0.0 else 0.1

    bands = [
        ('None', 0.0, thresholds['Slight'], '#f2f2f2'),
        ('Slight', thresholds['Slight'], thresholds['Moderate'], '#fff2b2'),
        ('Moderate', thresholds['Moderate'], thresholds['Extensive'], '#ffd9a3'),
        ('Extensive', thresholds['Extensive'], thresholds['Complete'], '#ffb3a6'),
        ('Complete', thresholds['Complete'], xmax, '#d8c7ff'),
    ]
    for name, x0, x1, color in bands:
        if x1 > x0:
            ax.axvspan(x0, x1, color=color, alpha=0.22, linewidth=0,
                       label=f'HAZUS {name}' if name != 'None' else None)

    damage_lines = [
        ('Slight', thresholds['Slight'], '#c7a100'),
        ('Moderate', thresholds['Moderate'], '#d97900'),
        ('Extensive', thresholds['Extensive'], '#c73b2f'),
        ('Complete', thresholds['Complete'], '#6b3fb5'),
    ]
    for name, sd, color in damage_lines:
        ax.axvline(sd, color=color, linestyle=':', linewidth=1.3,
                   label=f'{name} threshold')

    ax.plot(sd_hist, sa_hist, 'b-', linewidth=2.0, label='Capacity spectrum')
    ax.plot(capacity_sd, demand_sa, 'm--', linewidth=2.0,
            label='Demand spectrum (ASCE 41-23, secant $T_{eff}$)')

    if performance is not None:
        marker_label = ('Performance point' if performance['is_intersection']
                        else 'Closest approach')
        marker_color = 'darkgreen' if performance['is_intersection'] else 'dimgray'
        ax.plot(performance['sd'], performance['sa'], 'o', color=marker_color,
                markersize=7.5, label=marker_label)
        ax.annotate(
            f'{marker_label}\n'
            f'$S_d$={performance["sd"]:.4f} m\n'
            f'$S_a$={performance["sa"]:.3f} g',
            xy=(performance['sd'], performance['sa']),
            xytext=(10, 12),
            textcoords='offset points',
            fontsize=8,
            bbox=dict(boxstyle='round,pad=0.25', fc='white', ec='0.35', alpha=0.9),
            arrowprops=dict(arrowstyle='->', lw=0.8, color='0.35'))

    ax.set_xlim(left=0.0, right=xmax)
    ax.set_xlabel('Spectral displacement  $S_d$  (m)', fontsize=11)
    ax.set_ylabel('Spectral acceleration  $S_a$  (g)', fontsize=11)
    ax.set_title(
        f'{direction["label"]} Capacity-Demand Spectrum with HAZUS Damage States\n'
        f'$T_1={result["modal"]["T1"]:.3f}$ s,  '
        f'$\\alpha_1={result["modal"]["alpha1"]:.3f}$,  '
        f'$PF_1 \\cdot \\phi_1(ctrl)={result["modal"]["PF1_phi"]:.3f}$',
        fontsize=10)
    ax.axhline(0, color='k', linewidth=0.5)
    ax.axvline(0, color='k', linewidth=0.5)
    ax.legend(fontsize=7.6, ncol=2)
    ax.grid(alpha=0.35)
    fig.tight_layout()


def _plot_direction_hinges_3d(result):
    import matplotlib.pyplot as plt
    import matplotlib.lines as mlines

    colors = {
        'between IO and LS': 'gold',
        'between LS and CP': 'darkorange',
        '>= CP': 'red',
    }
    widths = {
        'between IO and LS': 3.0,
        'between LS and CP': 4.0,
        '>= CP': 5.0,
    }

    fig = plt.figure(figsize=(8.0, 7.0))
    ax = fig.add_subplot(111, projection='3d')

    frame_members = result.get('frame_members', [])
    coords = []
    for member in frame_members:
        xi, yi, zi = member['coord_i']
        xj, yj, zj = member['coord_j']
        coords.extend([member['coord_i'], member['coord_j']])
        ax.plot([xi, xj], [yi, yj], [zi, zj],
                color='0.78', linewidth=0.75, alpha=0.65, zorder=1)

    for member in result.get('hinging_members', []):
        xi, yi, zi = member['coord_i']
        xj, yj, zj = member['coord_j']
        category = member['category']
        color = colors.get(category, 'black')
        ax.plot([xi, xj], [yi, yj], [zi, zj],
                color=color,
                linewidth=widths.get(category, 3.0),
                solid_capstyle='round',
                zorder=4)
        xm = 0.5 * (xi + xj)
        ym = 0.5 * (yi + yj)
        zm = 0.5 * (zi + zj)
        ax.text(xm, ym, zm + 0.12, str(member['element']),
                color=color, fontsize=7, fontweight='bold',
                ha='center', va='center',
                bbox=dict(boxstyle='round,pad=0.15', fc='white', ec=color, alpha=0.82),
                zorder=6)

    if coords:
        xs = [c[0] for c in coords]
        ys = [c[1] for c in coords]
        zs = [c[2] for c in coords]
        ax.set_xlim(min(xs), max(xs))
        ax.set_ylim(min(ys), max(ys))
        ax.set_zlim(min(zs), max(zs))
        ax.set_box_aspect([
            max(max(xs) - min(xs), 1.0),
            max(max(ys) - min(ys), 1.0),
            max(max(zs) - min(zs), 1.0),
        ])

    counts = result.get('hinge_damage_counts', {})
    legend_items = [
        mlines.Line2D([], [], color='0.78', linewidth=1.5, label='Frame members'),
        mlines.Line2D([], [], color='gold', linewidth=3,
                      label=f'IO-LS ({counts.get("between IO and LS", 0)})'),
        mlines.Line2D([], [], color='darkorange', linewidth=4,
                      label=f'LS-CP ({counts.get("between LS and CP", 0)})'),
        mlines.Line2D([], [], color='red', linewidth=5,
                      label=f'>= CP ({counts.get(">= CP", 0)})'),
    ]
    ax.legend(handles=legend_items, loc='upper left', fontsize=8)
    ax.set_title(
        f'{result["direction"]["label"]} Original '
        'ACI 369.1M-17 Hinging Members at Performance Point',
        fontsize=10,
    )
    ax.set_xlabel('x (m)', fontsize=8)
    ax.set_ylabel('y (m)', fontsize=8)
    ax.set_zlabel('z (m)', fontsize=8)
    ax.tick_params(labelsize=7)
    ax.view_init(elev=22, azim=-50)
    fig.tight_layout()


def _print_four_direction_summary(results_by_direction):
    print('\n=== Four-direction original ADRS summary ===')
    header = ('Dir  Sd_pp(m)  Sa_pp(g)  T_eff(s)  Roof(mm)  '
              'Vbase(kN)  Dy(m)    Du(m)    IO-LS  LS-CP  >=CP  Status')
    print(header)
    print('-' * len(header))
    for direction_key in _DIRECTION_ORDER:
        result = results_by_direction.get(direction_key)
        if result is None:
            continue
        pp = result['performance_point']
        hz = result['hazus']
        hc = result.get('hinge_damage_counts', {})
        if pp is None:
            print(f'{result["direction"]["label"]:>3}  no positive capacity-demand data')
            continue
        status = 'intersection' if pp['is_intersection'] else 'closest'
        print(
            f'{result["direction"]["label"]:>3}  '
            f'{pp["sd"]:8.5f}  {pp["sa"]:8.5f}  {pp["teff"]:8.4f}  '
            f'{pp["roof_disp_mm"]:8.2f}  {pp["base_shear_kN"]:9.2f}  '
            f'{hz["Dy"]:7.5f}  {hz["Du"]:7.5f}  '
            f'{hc.get("between IO and LS", 0):5d}  '
            f'{hc.get("between LS and CP", 0):5d}  '
            f'{hc.get(">= CP", 0):4d}  {status}'
        )

    print('\n=== ACI 369.1M-17 hinge counts by member type ===')
    hinge_header = 'Dir  Type      IO-LS  LS-CP  >=CP  Total'
    print(hinge_header)
    print('-' * len(hinge_header))
    for direction_key in _DIRECTION_ORDER:
        result = results_by_direction.get(direction_key)
        if result is None:
            continue
        hc = result.get('hinge_damage_counts', {})
        by_type = hc.get('by_type', {})
        for member_type in ['beams', 'columns']:
            counts = by_type.get(member_type, {})
            print(
                f'{result["direction"]["label"]:>3}  '
                f'{member_type:<7}  '
                f'{counts.get("between IO and LS", 0):5d}  '
                f'{counts.get("between LS and CP", 0):5d}  '
                f'{counts.get(">= CP", 0):4d}  '
                f'{counts.get("total", 0):5d}'
            )


def _run_four_direction_adrs_parent():
    import matplotlib.pyplot as plt

    script_path = os.path.abspath(__file__)
    results_by_direction = {}
    with tempfile.TemporaryDirectory(prefix='ce259_adrs_') as tmpdir:
        for direction_key in _DIRECTION_ORDER:
            cfg = _DIRECTION_CONFIGS[direction_key]
            out_path = os.path.join(tmpdir, f'{direction_key}.json')
            env = os.environ.copy()
            env[_ADRS_WORKER_ENV] = '1'
            env[_ADRS_DIRECTION_ENV] = direction_key
            env[_ADRS_OUTPUT_ENV] = out_path
            env.setdefault('MPLBACKEND', 'Agg')
            print(f'Running {cfg["label"]} Original pushover worker...')
            proc = subprocess.run(
                [sys.executable, script_path],
                cwd=os.path.dirname(script_path),
                env=env,
                text=True,
                capture_output=True,
            )
            if proc.stdout:
                print(proc.stdout, end='' if proc.stdout.endswith('\n') else '\n')
            if proc.returncode != 0:
                if proc.stderr:
                    print(proc.stderr, file=sys.stderr, end='' if proc.stderr.endswith('\n') else '\n')
                return proc.returncode
            if proc.stderr:
                print(proc.stderr, file=sys.stderr, end='' if proc.stderr.endswith('\n') else '\n')
            with open(out_path, 'r', encoding='utf-8') as f:
                results_by_direction[direction_key] = json.load(f)

    _print_four_direction_summary(results_by_direction)
    for direction_key in _DIRECTION_ORDER:
        result = results_by_direction.get(direction_key)
        if result is not None:
            _plot_direction_adrs(result)
            _plot_direction_hinges_3d(result)
    plt.show()
    return 0


if os.environ.get(_ADRS_WORKER_ENV) != '1':
    sys.exit(_run_four_direction_adrs_parent())

import openseespy.opensees as ops
try:
    import opsvis as opsv
except ImportError:
    opsv = None
import math
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.animation as _animation

_CURRENT_DIRECTION_KEY = os.environ.get(_ADRS_DIRECTION_ENV, 'pos_x')
_CURRENT_DIRECTION = _DIRECTION_CONFIGS.get(_CURRENT_DIRECTION_KEY, _DIRECTION_CONFIGS['pos_x'])
_ANALYSIS_LABEL = 'Original'
_CTRL_NODE = 76
_CTRL_DOF = _CURRENT_DIRECTION['dof']
_DIRECTION_SIGN = _CURRENT_DIRECTION['sign']
_DIRECTION_LABEL = _CURRENT_DIRECTION['label']
_SHOW_SINGLE_DIRECTION_DETAIL = False

ops.wipe()
ops.model('basic', '-ndm', 3, '-ndf', 6)

# =====================================================================
# NODES
# =====================================================================
ops.node(    1,  0.0000,  14.0000,  -2.0000)
ops.node(    2,  0.0000,  14.0000,  0.0000)
ops.node(    3,  0.0000,  10.0000,  -2.0000)
ops.node(    4,  0.0000,  10.0000,  0.0000)
ops.node(    5,  0.0000,  4.0000,  -2.0000)
ops.node(    6,  0.0000,  4.0000,  0.0000)
ops.node(    7,  0.0000,  0.0000,  -2.0000)
ops.node(    8,  0.0000,  0.0000,  0.0000)
ops.node(    9,  5.5000,  14.0000,  -2.0000)
ops.node(   10,  5.5000,  14.0000,  0.0000)
ops.node(   11,  5.5000,  10.0000,  -2.0000)
ops.node(   12,  5.5000,  10.0000,  0.0000)
ops.node(   13,  5.5000,  4.0000,  -2.0000)
ops.node(   14,  5.5000,  4.0000,  0.0000)
ops.node(   15,  5.5000,  0.0000,  -2.0000)
ops.node(   16,  5.5000,  0.0000,  0.0000)
ops.node(   17,  13.0000,  14.0000,  -2.0000)
ops.node(   18,  13.0000,  14.0000,  0.0000)
ops.node(   19,  13.0000,  10.0000,  -2.0000)
ops.node(   20,  13.0000,  10.0000,  0.0000)
ops.node(   21,  13.0000,  4.0000,  -2.0000)
ops.node(   22,  13.0000,  4.0000,  0.0000)
ops.node(   23,  13.0000,  0.0000,  -2.0000)
ops.node(   24,  13.0000,  0.0000,  0.0000)
ops.node(   25,  18.5000,  0.0000,  -2.0000)
ops.node(   26,  18.5000,  0.0000,  0.0000)
ops.node(   27,  18.5000,  4.0000,  -2.0000)
ops.node(   28,  18.5000,  4.0000,  0.0000)
ops.node(   29,  18.5000,  10.0000,  -2.0000)
ops.node(   30,  18.5000,  10.0000,  0.0000)
ops.node(   31,  18.5000,  14.0000,  -2.0000)
ops.node(   32,  18.5000,  14.0000,  0.0000)
ops.node(   33,  0.0000,  14.0000,  3.6000)
ops.node(   34,  0.0000,  10.0000,  3.6000)
ops.node(   35,  0.0000,  4.0000,  3.6000)
ops.node(   36,  0.0000,  0.0000,  3.6000)
ops.node(   37,  5.5000,  14.0000,  3.6000)
ops.node(   38,  5.5000,  10.0000,  3.6000)
ops.node(   39,  5.5000,  4.0000,  3.6000)
ops.node(   40,  5.5000,  0.0000,  3.6000)
ops.node(   41,  13.0000,  14.0000,  3.6000)
ops.node(   42,  13.0000,  10.0000,  3.6000)
ops.node(   43,  13.0000,  4.0000,  3.6000)
ops.node(   44,  13.0000,  0.0000,  3.6000)
ops.node(   45,  18.5000,  0.0000,  3.6000)
ops.node(   46,  18.5000,  4.0000,  3.6000)
ops.node(   47,  18.5000,  10.0000,  3.6000)
ops.node(   48,  18.5000,  14.0000,  3.6000)
ops.node(   49,  0.0000,  14.0000,  7.2000)
ops.node(   50,  0.0000,  14.0000,  10.8000)
ops.node(   51,  0.0000,  10.0000,  7.2000)
ops.node(   52,  0.0000,  10.0000,  10.8000)
ops.node(   53,  0.0000,  4.0000,  7.2000)
ops.node(   54,  0.0000,  4.0000,  10.8000)
ops.node(   55,  0.0000,  0.0000,  7.2000)
ops.node(   56,  0.0000,  0.0000,  10.8000)
ops.node(   57,  5.5000,  14.0000,  7.2000)
ops.node(   58,  5.5000,  14.0000,  10.8000)
ops.node(   59,  5.5000,  10.0000,  7.2000)
ops.node(   60,  5.5000,  10.0000,  10.8000)
ops.node(   61,  5.5000,  4.0000,  7.2000)
ops.node(   62,  5.5000,  4.0000,  10.8000)
ops.node(   63,  5.5000,  0.0000,  7.2000)
ops.node(   64,  5.5000,  0.0000,  10.8000)
ops.node(   65,  13.0000,  14.0000,  7.2000)
ops.node(   66,  13.0000,  14.0000,  10.8000)
ops.node(   67,  13.0000,  10.0000,  7.2000)
ops.node(   68,  13.0000,  10.0000,  10.8000)
ops.node(   69,  13.0000,  4.0000,  7.2000)
ops.node(   70,  13.0000,  4.0000,  10.8000)
ops.node(   71,  13.0000,  0.0000,  7.2000)
ops.node(   72,  13.0000,  0.0000,  10.8000)
ops.node(   73,  18.5000,  0.0000,  7.2000)
ops.node(   74,  18.5000,  0.0000,  10.8000)
ops.node(   75,  18.5000,  4.0000,  7.2000)
ops.node(   76,  18.5000,  4.0000,  10.8000)
ops.node(   77,  18.5000,  10.0000,  7.2000)
ops.node(   78,  18.5000,  10.0000,  10.8000)
ops.node(   79,  18.5000,  14.0000,  7.2000)
ops.node(   80,  18.5000,  14.0000,  10.8000)
ops.node(   81,  18.5000,  4.0000,  13.8000)
ops.node(   82,  18.5000,  10.0000,  13.8000)
ops.node(   83,  13.0000,  10.0000,  13.8000)
ops.node(   84,  13.0000,  4.0000,  13.8000)
ops.node(   85,  14.8000,  5.7000,  3.6000)
ops.node(   86,  18.5000,  5.7000,  3.6000)
ops.node(   87,  14.8000,  8.3000,  3.6000)
ops.node(   88,  18.5000,  8.3000,  3.6000)
ops.node(   89,  14.8000,  5.7000,  0.0000)
ops.node(   90,  18.5000,  5.7000,  0.0000)
ops.node(   91,  14.8000,  8.3000,  0.0000)
ops.node(   92,  18.5000,  8.3000,  0.0000)
ops.node(   93,  14.8000,  5.7000,  10.8000)
ops.node(   94,  18.5000,  5.7000,  10.8000)
ops.node(   95,  14.8000,  8.3000,  10.8000)
ops.node(   96,  18.5000,  8.3000,  10.8000)
ops.node(   97,  14.8000,  5.7000,  7.2000)
ops.node(   98,  18.5000,  5.7000,  7.2000)
ops.node(   99,  14.8000,  8.3000,  7.2000)
ops.node(  100,  18.5000,  8.3000,  7.2000)
ops.node(  101,  14.8000,  4.0000,  13.8000)
ops.node(  102,  14.8000,  10.0000,  13.8000)
ops.node(  103,  14.8000,  5.7000,  13.8000)
ops.node(  104,  18.5000,  5.7000,  13.8000)
ops.node(  105,  14.8000,  8.3000,  13.8000)
ops.node(  106,  18.5000,  8.3000,  13.8000)
ops.node(  107,  14.8000,  4.0000,  10.8000)
ops.node(  108,  14.8000,  10.0000,  10.8000)
ops.node(  109,  14.8000,  4.0000,  3.6000)
ops.node(  110,  14.8000,  10.0000,  3.6000)
ops.node(  111,  14.8000,  4.0000,  0.0000)
ops.node(  112,  14.8000,  10.0000,  0.0000)
ops.node(  113,  14.8000,  4.0000,  7.2000)
ops.node(  114,  14.8000,  10.0000,  7.2000)

# =====================================================================
# BOUNDARY CONDITIONS
# =====================================================================
ops.fix(1, 1, 1, 1, 1, 1, 1)
ops.fix(3, 1, 1, 1, 1, 1, 1)
ops.fix(5, 1, 1, 1, 1, 1, 1)
ops.fix(7, 1, 1, 1, 1, 1, 1)
ops.fix(9, 1, 1, 1, 1, 1, 1)
ops.fix(11, 1, 1, 1, 1, 1, 1)
ops.fix(13, 1, 1, 1, 1, 1, 1)
ops.fix(15, 1, 1, 1, 1, 1, 1)
ops.fix(17, 1, 1, 1, 1, 1, 1)
ops.fix(19, 1, 1, 1, 1, 1, 1)
ops.fix(21, 1, 1, 1, 1, 1, 1)
ops.fix(23, 1, 1, 1, 1, 1, 1)
ops.fix(25, 1, 1, 1, 1, 1, 1)
ops.fix(27, 1, 1, 1, 1, 1, 1)
ops.fix(29, 1, 1, 1, 1, 1, 1)
ops.fix(31, 1, 1, 1, 1, 1, 1)

# =====================================================================
# UNIAXIAL MATERIALS  (Concrete02 + Steel02 + MinMax wrappers)
# =====================================================================
# f'c = 21.0 MPa,  fy = 414.0 MPa
ops.uniaxialMaterial('Concrete02', 11,
    -21000.0, -0.002, -4200.0, -0.0038,
    0.1, 2841.2, 1.0769e+06)   # Concrete02  (f'c=21.0 MPa)
ops.uniaxialMaterial('Steel02', 13,
    414000.0, 2.100000e+08, 0.18, 18.0, 0.925, 0.15)   # Steel02  (fy=414.0 MPa)
# f'c = 28.0 MPa,  fy = 414.0 MPa
ops.uniaxialMaterial('Concrete02', 12,
    -28000.0, -0.002, -5600.0, -0.0038,
    0.1, 3280.7, 1.2435e+06)   # Concrete02  (f'c=28.0 MPa)
ops.uniaxialMaterial('Steel02', 14,
    414000.0, 2.100000e+08, 0.18, 18.0, 0.925, 0.15)   # Steel02  (fy=414.0 MPa)

# MinMax wrappers (limit strain at ±fracture/crush)
ops.uniaxialMaterial('MinMax', 1,  11, '-min', -0.010)                # concrete
ops.uniaxialMaterial('MinMax', 2, 13, '-min', -0.10, '-max', 0.10)  # steel
ops.uniaxialMaterial('MinMax', 3,  12, '-min', -0.010)                # concrete
ops.uniaxialMaterial('MinMax', 4, 14, '-min', -0.10, '-max', 0.10)  # steel

# =====================================================================
# FIBER CROSS-SECTIONS
# =====================================================================
# Section 1: Beam [B 250 X 400]  b=250 mm × h=400 mm
ops.section('Fiber', 1, '-GJ', 1.0)
ops.patch('rect', 1, 30,  3,  -0.1250, 0.1400,  0.1250, 0.2000)     # top cover
ops.patch('rect', 1, 30,  3,  -0.1250, -0.2000,    0.1250, -0.1400) # bottom cover
ops.patch('rect', 1,  8, 24,  -0.1250, -0.1400, -0.0650, 0.1400)  # left cover
ops.patch('rect', 1,  8, 24,  0.0650, -0.1400,  0.1250, 0.1400)   # right cover
ops.patch('rect', 1, 24, 24,  -0.0650, -0.1400,  0.0650, 0.1400)  # core
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0570, 0.1320,  -0.0570, 0.1320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0570, 0.1320,  0.0570, 0.1320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0570, -0.1320,  -0.0570, -0.1320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0190, -0.1320,  -0.0190, -0.1320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0190, -0.1320,  0.0190, -0.1320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0570, -0.1320,  0.0570, -0.1320)   # bot  D16

# Section 2: Beam [B 300 X 500]  b=300 mm × h=500 mm
ops.section('Fiber', 2, '-GJ', 1.0)
ops.patch('rect', 1, 30,  3,  -0.1500, 0.1900,  0.1500, 0.2500)     # top cover
ops.patch('rect', 1, 30,  3,  -0.1500, -0.2500,    0.1500, -0.1900) # bottom cover
ops.patch('rect', 1,  8, 24,  -0.1500, -0.1900, -0.0900, 0.1900)  # left cover
ops.patch('rect', 1,  8, 24,  0.0900, -0.1900,  0.1500, 0.1900)   # right cover
ops.patch('rect', 1, 24, 24,  -0.0900, -0.1900,  0.0900, 0.1900)  # core
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0820, 0.1820,  -0.0820, 0.1820)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0492, 0.1820,  -0.0492, 0.1820)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0164, 0.1820,  -0.0164, 0.1820)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0164, 0.1820,  0.0164, 0.1820)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0492, 0.1820,  0.0492, 0.1820)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0820, 0.1820,  0.0820, 0.1820)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0820, -0.1820,  -0.0820, -0.1820)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0000, -0.1820,  0.0000, -0.1820)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0820, -0.1820,  0.0820, -0.1820)   # bot  D16

# Section 3: Beam [B 350 X 600]  b=350 mm × h=600 mm
ops.section('Fiber', 3, '-GJ', 1.0)
ops.patch('rect', 1, 30,  3,  -0.1750, 0.2400,  0.1750, 0.3000)     # top cover
ops.patch('rect', 1, 30,  3,  -0.1750, -0.3000,    0.1750, -0.2400) # bottom cover
ops.patch('rect', 1,  8, 24,  -0.1750, -0.2400, -0.1150, 0.2400)  # left cover
ops.patch('rect', 1,  8, 24,  0.1150, -0.2400,  0.1750, 0.2400)   # right cover
ops.patch('rect', 1, 24, 24,  -0.1150, -0.2400,  0.1150, 0.2400)  # core
ops.layer('straight', 2, 1, 2.010619e-04,  -0.1070, 0.2320,  -0.1070, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0803, 0.2320,  -0.0803, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0535, 0.2320,  -0.0535, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0267, 0.2320,  -0.0267, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0000, 0.2320,  0.0000, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0267, 0.2320,  0.0267, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0535, 0.2320,  0.0535, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0803, 0.2320,  0.0803, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.1070, 0.2320,  0.1070, 0.2320)   # top  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.1070, -0.2320,  -0.1070, -0.2320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  -0.0535, -0.2320,  -0.0535, -0.2320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0000, -0.2320,  0.0000, -0.2320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.0535, -0.2320,  0.0535, -0.2320)   # bot  D16
ops.layer('straight', 2, 1, 2.010619e-04,  0.1070, -0.2320,  0.1070, -0.2320)   # bot  D16

# Section 4: Column [C 450 X 450]  b=450 mm × d=450 mm
ops.section('Fiber', 4, '-GJ', 1.0)
ops.patch('rect', 3, 30,  3,  -0.2250, 0.1850,  0.2250, 0.2250)     # top cover
ops.patch('rect', 3, 30,  3,  -0.2250, -0.2250,    0.2250, -0.1850) # bottom cover
ops.patch('rect', 3,  8, 24,  -0.2250, -0.1850, -0.1850, 0.1850)  # left cover
ops.patch('rect', 3,  8, 24,  0.1850, -0.1850,  0.2250, 0.1850)   # right cover
ops.patch('rect', 3, 24, 24,  -0.1850, -0.1850,  0.1850, 0.1850)  # core
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, 0.1770,  -0.1770, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1416, 0.1770,  -0.1416, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1062, 0.1770,  -0.1062, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.0708, 0.1770,  -0.0708, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.0354, 0.1770,  -0.0354, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.0000, 0.1770,  0.0000, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.0354, 0.1770,  0.0354, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.0708, 0.1770,  0.0708, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1062, 0.1770,  0.1062, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1416, 0.1770,  0.1416, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, 0.1770,  0.1770, 0.1770)   # top  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, -0.1770,  -0.1770, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1416, -0.1770,  -0.1416, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1062, -0.1770,  -0.1062, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.0708, -0.1770,  -0.0708, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.0354, -0.1770,  -0.0354, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.0000, -0.1770,  0.0000, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.0354, -0.1770,  0.0354, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.0708, -0.1770,  0.0708, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1062, -0.1770,  0.1062, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1416, -0.1770,  0.1416, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, -0.1770,  0.1770, -0.1770)   # bot  D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, -0.1448,  -0.1770, -0.1448)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, -0.1126,  -0.1770, -0.1126)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, -0.0805,  -0.1770, -0.0805)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, -0.0483,  -0.1770, -0.0483)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, -0.0161,  -0.1770, -0.0161)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, 0.0161,  -0.1770, 0.0161)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, 0.0483,  -0.1770, 0.0483)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, 0.0805,  -0.1770, 0.0805)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, 0.1126,  -0.1770, 0.1126)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  -0.1770, 0.1448,  -0.1770, 0.1448)  # side L D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, -0.1448,  0.1770, -0.1448)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, -0.1126,  0.1770, -0.1126)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, -0.0805,  0.1770, -0.0805)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, -0.0483,  0.1770, -0.0483)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, -0.0161,  0.1770, -0.0161)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, 0.0161,  0.1770, 0.0161)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, 0.0483,  0.1770, 0.0483)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, 0.0805,  0.1770, 0.0805)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, 0.1126,  0.1770, 0.1126)  # side R D16
ops.layer('straight', 4, 1, 2.010619e-04,  0.1770, 0.1448,  0.1770, 0.1448)  # side R D16


# =====================================================================
# GEOMETRIC TRANSFORMATIONS
# =====================================================================
ops.geomTransf('PDelta', 1,  1.0, 0.0, 0.0)   # columns along Z
ops.geomTransf('PDelta', 2,  1.0, 0.0, 0.0)   # Y-axis beams
ops.geomTransf('PDelta', 3,  0.0, 1.0, 0.0)   # X-axis beams
ops.geomTransf('PDelta', 4,  0.0, 0.0, 1.0)   # diagonal / other

# =====================================================================
# BEAM INTEGRATIONS  (Gauss-Lobatto, 5 pts)
# =====================================================================
ops.beamIntegration('Lobatto', 1, 1, 5)
ops.beamIntegration('Lobatto', 2, 2, 5)
ops.beamIntegration('Lobatto', 3, 3, 5)
ops.beamIntegration('Lobatto', 4, 4, 5)

# =====================================================================
# COLUMN ELEMENTS  (forceBeamColumn,  geomTransf=1)
# =====================================================================
ops.element('forceBeamColumn',     1,     1,     2, 1, 4)   # GF|C13
ops.element('forceBeamColumn',     2,     3,     4, 1, 4)   # GF|C9
ops.element('forceBeamColumn',     3,     5,     6, 1, 4)   # GF|C5
ops.element('forceBeamColumn',     4,     7,     8, 1, 4)   # GF|C1
ops.element('forceBeamColumn',     5,     9,    10, 1, 4)   # GF|C14
ops.element('forceBeamColumn',     6,    11,    12, 1, 4)   # GF|C10
ops.element('forceBeamColumn',     7,    13,    14, 1, 4)   # GF|C6
ops.element('forceBeamColumn',     8,    15,    16, 1, 4)   # GF|C2
ops.element('forceBeamColumn',     9,    17,    18, 1, 4)   # GF|C15
ops.element('forceBeamColumn',    10,    19,    20, 1, 4)   # GF|C11
ops.element('forceBeamColumn',    11,    21,    22, 1, 4)   # GF|C7
ops.element('forceBeamColumn',    12,    23,    24, 1, 4)   # GF|C3
ops.element('forceBeamColumn',    13,    25,    26, 1, 4)   # GF|C4
ops.element('forceBeamColumn',    14,    27,    28, 1, 4)   # GF|C8
ops.element('forceBeamColumn',    15,    29,    30, 1, 4)   # GF|C12
ops.element('forceBeamColumn',    16,    31,    32, 1, 4)   # GF|C16
ops.element('forceBeamColumn',    17,     2,    33, 1, 4)   # 2F|C13
ops.element('forceBeamColumn',    18,     4,    34, 1, 4)   # 2F|C9
ops.element('forceBeamColumn',    19,     6,    35, 1, 4)   # 2F|C5
ops.element('forceBeamColumn',    20,     8,    36, 1, 4)   # 2F|C1
ops.element('forceBeamColumn',    21,    10,    37, 1, 4)   # 2F|C14
ops.element('forceBeamColumn',    22,    12,    38, 1, 4)   # 2F|C10
ops.element('forceBeamColumn',    23,    14,    39, 1, 4)   # 2F|C6
ops.element('forceBeamColumn',    24,    16,    40, 1, 4)   # 2F|C2
ops.element('forceBeamColumn',    25,    18,    41, 1, 4)   # 2F|C15
ops.element('forceBeamColumn',    26,    20,    42, 1, 4)   # 2F|C11
ops.element('forceBeamColumn',    27,    22,    43, 1, 4)   # 2F|C7
ops.element('forceBeamColumn',    28,    24,    44, 1, 4)   # 2F|C3
ops.element('forceBeamColumn',    29,    26,    45, 1, 4)   # 2F|C4
ops.element('forceBeamColumn',    30,    28,    46, 1, 4)   # 2F|C8
ops.element('forceBeamColumn',    31,    30,    47, 1, 4)   # 2F|C12
ops.element('forceBeamColumn',    32,    32,    48, 1, 4)   # 2F|C16
ops.element('forceBeamColumn',    33,    49,    50, 1, 4)   # ROOF DECK|C13
ops.element('forceBeamColumn',    34,    51,    52, 1, 4)   # ROOF DECK|C9
ops.element('forceBeamColumn',    35,    53,    54, 1, 4)   # ROOF DECK|C5
ops.element('forceBeamColumn',    36,    55,    56, 1, 4)   # ROOF DECK|C1
ops.element('forceBeamColumn',    37,    57,    58, 1, 4)   # ROOF DECK|C14
ops.element('forceBeamColumn',    38,    59,    60, 1, 4)   # ROOF DECK|C10
ops.element('forceBeamColumn',    39,    61,    62, 1, 4)   # ROOF DECK|C6
ops.element('forceBeamColumn',    40,    63,    64, 1, 4)   # ROOF DECK|C2
ops.element('forceBeamColumn',    41,    65,    66, 1, 4)   # ROOF DECK|C15
ops.element('forceBeamColumn',    42,    67,    68, 1, 4)   # ROOF DECK|C11
ops.element('forceBeamColumn',    43,    69,    70, 1, 4)   # ROOF DECK|C7
ops.element('forceBeamColumn',    44,    71,    72, 1, 4)   # ROOF DECK|C3
ops.element('forceBeamColumn',    45,    73,    74, 1, 4)   # ROOF DECK|C4
ops.element('forceBeamColumn',    46,    75,    76, 1, 4)   # ROOF DECK|C8
ops.element('forceBeamColumn',    47,    77,    78, 1, 4)   # ROOF DECK|C12
ops.element('forceBeamColumn',    48,    79,    80, 1, 4)   # ROOF DECK|C16
ops.element('forceBeamColumn',    49,    33,    49, 1, 4)   # 3F|C13
ops.element('forceBeamColumn',    50,    34,    51, 1, 4)   # 3F|C9
ops.element('forceBeamColumn',    51,    35,    53, 1, 4)   # 3F|C5
ops.element('forceBeamColumn',    52,    36,    55, 1, 4)   # 3F|C1
ops.element('forceBeamColumn',    53,    37,    57, 1, 4)   # 3F|C14
ops.element('forceBeamColumn',    54,    38,    59, 1, 4)   # 3F|C10
ops.element('forceBeamColumn',    55,    39,    61, 1, 4)   # 3F|C6
ops.element('forceBeamColumn',    56,    40,    63, 1, 4)   # 3F|C2
ops.element('forceBeamColumn',    57,    41,    65, 1, 4)   # 3F|C15
ops.element('forceBeamColumn',    58,    42,    67, 1, 4)   # 3F|C11
ops.element('forceBeamColumn',    59,    43,    69, 1, 4)   # 3F|C7
ops.element('forceBeamColumn',    60,    44,    71, 1, 4)   # 3F|C3
ops.element('forceBeamColumn',    61,    45,    73, 1, 4)   # 3F|C4
ops.element('forceBeamColumn',    62,    46,    75, 1, 4)   # 3F|C8
ops.element('forceBeamColumn',    63,    47,    77, 1, 4)   # 3F|C12
ops.element('forceBeamColumn',    64,    48,    79, 1, 4)   # 3F|C16
ops.element('forceBeamColumn',    65,    76,    81, 1, 4)   # ROOF STAIR|C8
ops.element('forceBeamColumn',    66,    78,    82, 1, 4)   # ROOF STAIR|C12
ops.element('forceBeamColumn',    67,    68,    83, 1, 4)   # ROOF STAIR|C11
ops.element('forceBeamColumn',    68,    70,    84, 1, 4)   # ROOF STAIR|C7

# =====================================================================
# BEAM ELEMENTS  (forceBeamColumn)
# =====================================================================
ops.element('forceBeamColumn',    69,     2,    10, 3, 3)   # GF|B25
ops.element('forceBeamColumn',    70,    10,    18, 3, 3)   # GF|B26
ops.element('forceBeamColumn',    71,    18,    32, 3, 3)   # GF|B27
ops.element('forceBeamColumn',    72,     8,     6, 2, 2)   # GF|B4
ops.element('forceBeamColumn',    73,     6,     4, 2, 2)   # GF|B12
ops.element('forceBeamColumn',    74,     4,     2, 2, 2)   # GF|B21
ops.element('forceBeamColumn',    75,     4,    12, 3, 3)   # GF|B18
ops.element('forceBeamColumn',    76,    12,    20, 3, 3)   # GF|B19
ops.element('forceBeamColumn',    77,    20,    30, 3, 3)   # GF|B20
ops.element('forceBeamColumn',    78,     6,    14, 3, 3)   # GF|B8
ops.element('forceBeamColumn',    79,    14,    22, 3, 3)   # GF|B9
ops.element('forceBeamColumn',    80,    22,    28, 3, 3)   # GF|B10
ops.element('forceBeamColumn',    81,     8,    16, 3, 3)   # GF|B1
ops.element('forceBeamColumn',    82,    16,    24, 3, 3)   # GF|B2
ops.element('forceBeamColumn',    83,    24,    26, 3, 3)   # GF|B3
ops.element('forceBeamColumn',    84,    16,    14, 2, 2)   # GF|B5
ops.element('forceBeamColumn',    85,    14,    12, 2, 2)   # GF|B13
ops.element('forceBeamColumn',    86,    12,    10, 2, 2)   # GF|B22
ops.element('forceBeamColumn',    87,    24,    22, 2, 2)   # GF|B6
ops.element('forceBeamColumn',    88,    22,    20, 2, 2)   # GF|B14
ops.element('forceBeamColumn',    89,    20,    18, 2, 2)   # GF|B23
ops.element('forceBeamColumn',    90,    26,    28, 2, 2)   # GF|B7
ops.element('forceBeamColumn',    91,    28,    30, 2, 2)   # GF|B16
ops.element('forceBeamColumn',    92,    30,    32, 2, 2)   # GF|B24
ops.element('forceBeamColumn',    93,    33,    37, 3, 3)   # 2F|B25
ops.element('forceBeamColumn',    94,    37,    41, 3, 3)   # 2F|B26
ops.element('forceBeamColumn',    95,    41,    48, 3, 3)   # 2F|B27
ops.element('forceBeamColumn',    96,    36,    35, 2, 3)   # 2F|B4
ops.element('forceBeamColumn',    97,    35,    34, 2, 3)   # 2F|B12
ops.element('forceBeamColumn',    98,    34,    33, 2, 3)   # 2F|B21
ops.element('forceBeamColumn',    99,    34,    38, 3, 3)   # 2F|B18
ops.element('forceBeamColumn',   100,    38,    42, 3, 3)   # 2F|B19
ops.element('forceBeamColumn',   101,    42,    47, 3, 3)   # 2F|B20
ops.element('forceBeamColumn',   102,    35,    39, 3, 3)   # 2F|B8
ops.element('forceBeamColumn',   103,    39,    43, 3, 3)   # 2F|B9
ops.element('forceBeamColumn',   104,    43,    46, 3, 3)   # 2F|B10
ops.element('forceBeamColumn',   105,    36,    40, 3, 3)   # 2F|B1
ops.element('forceBeamColumn',   106,    40,    44, 3, 3)   # 2F|B2
ops.element('forceBeamColumn',   107,    44,    45, 3, 3)   # 2F|B3
ops.element('forceBeamColumn',   108,    40,    39, 2, 3)   # 2F|B5
ops.element('forceBeamColumn',   109,    39,    38, 2, 3)   # 2F|B13
ops.element('forceBeamColumn',   110,    38,    37, 2, 3)   # 2F|B22
ops.element('forceBeamColumn',   111,    44,    43, 2, 3)   # 2F|B6
ops.element('forceBeamColumn',   112,    43,    42, 2, 3)   # 2F|B14
ops.element('forceBeamColumn',   113,    42,    41, 2, 3)   # 2F|B23
ops.element('forceBeamColumn',   114,    45,    46, 2, 3)   # 2F|B7
ops.element('forceBeamColumn',   115,    46,    47, 2, 3)   # 2F|B16
ops.element('forceBeamColumn',   116,    47,    48, 2, 3)   # 2F|B24
ops.element('forceBeamColumn',   117,    85,    86, 3, 1)   # 2F|B11
ops.element('forceBeamColumn',   118,    87,    88, 3, 1)   # 2F|B17
ops.element('forceBeamColumn',   119,    89,    90, 3, 1)   # GF|B11
ops.element('forceBeamColumn',   120,    91,    92, 3, 1)   # GF|B17
ops.element('forceBeamColumn',   121,    50,    58, 3, 2)   # ROOF DECK|B25
ops.element('forceBeamColumn',   122,    58,    66, 3, 2)   # ROOF DECK|B26
ops.element('forceBeamColumn',   123,    66,    80, 3, 2)   # ROOF DECK|B27
ops.element('forceBeamColumn',   124,    56,    54, 2, 2)   # ROOF DECK|B4
ops.element('forceBeamColumn',   125,    54,    52, 2, 2)   # ROOF DECK|B12
ops.element('forceBeamColumn',   126,    52,    50, 2, 2)   # ROOF DECK|B21
ops.element('forceBeamColumn',   127,    52,    60, 3, 2)   # ROOF DECK|B18
ops.element('forceBeamColumn',   128,    60,    68, 3, 2)   # ROOF DECK|B19
ops.element('forceBeamColumn',   129,    68,    78, 3, 2)   # ROOF DECK|B20
ops.element('forceBeamColumn',   130,    54,    62, 3, 2)   # ROOF DECK|B8
ops.element('forceBeamColumn',   131,    62,    70, 3, 2)   # ROOF DECK|B9
ops.element('forceBeamColumn',   132,    70,    76, 3, 2)   # ROOF DECK|B10
ops.element('forceBeamColumn',   133,    56,    64, 3, 2)   # ROOF DECK|B1
ops.element('forceBeamColumn',   134,    64,    72, 3, 2)   # ROOF DECK|B2
ops.element('forceBeamColumn',   135,    72,    74, 3, 2)   # ROOF DECK|B3
ops.element('forceBeamColumn',   136,    64,    62, 2, 2)   # ROOF DECK|B5
ops.element('forceBeamColumn',   137,    62,    60, 2, 2)   # ROOF DECK|B13
ops.element('forceBeamColumn',   138,    60,    58, 2, 2)   # ROOF DECK|B22
ops.element('forceBeamColumn',   139,    72,    70, 2, 2)   # ROOF DECK|B6
ops.element('forceBeamColumn',   140,    70,    68, 2, 2)   # ROOF DECK|B14
ops.element('forceBeamColumn',   141,    68,    66, 2, 2)   # ROOF DECK|B23
ops.element('forceBeamColumn',   142,    74,    76, 2, 2)   # ROOF DECK|B7
ops.element('forceBeamColumn',   143,    76,    78, 2, 2)   # ROOF DECK|B16
ops.element('forceBeamColumn',   144,    78,    80, 2, 2)   # ROOF DECK|B24
ops.element('forceBeamColumn',   145,    93,    94, 3, 1)   # ROOF DECK|B11
ops.element('forceBeamColumn',   146,    95,    96, 3, 1)   # ROOF DECK|B17
ops.element('forceBeamColumn',   147,    49,    57, 3, 3)   # 3F|B25
ops.element('forceBeamColumn',   148,    57,    65, 3, 3)   # 3F|B26
ops.element('forceBeamColumn',   149,    65,    79, 3, 3)   # 3F|B27
ops.element('forceBeamColumn',   150,    55,    53, 2, 3)   # 3F|B4
ops.element('forceBeamColumn',   151,    53,    51, 2, 3)   # 3F|B12
ops.element('forceBeamColumn',   152,    51,    49, 2, 3)   # 3F|B21
ops.element('forceBeamColumn',   153,    51,    59, 3, 3)   # 3F|B18
ops.element('forceBeamColumn',   154,    59,    67, 3, 3)   # 3F|B19
ops.element('forceBeamColumn',   155,    67,    77, 3, 3)   # 3F|B20
ops.element('forceBeamColumn',   156,    53,    61, 3, 3)   # 3F|B8
ops.element('forceBeamColumn',   157,    61,    69, 3, 3)   # 3F|B9
ops.element('forceBeamColumn',   158,    69,    75, 3, 3)   # 3F|B10
ops.element('forceBeamColumn',   159,    55,    63, 3, 3)   # 3F|B1
ops.element('forceBeamColumn',   160,    63,    71, 3, 3)   # 3F|B2
ops.element('forceBeamColumn',   161,    71,    73, 3, 3)   # 3F|B3
ops.element('forceBeamColumn',   162,    63,    61, 2, 3)   # 3F|B5
ops.element('forceBeamColumn',   163,    61,    59, 2, 3)   # 3F|B13
ops.element('forceBeamColumn',   164,    59,    57, 2, 3)   # 3F|B22
ops.element('forceBeamColumn',   165,    71,    69, 2, 3)   # 3F|B6
ops.element('forceBeamColumn',   166,    69,    67, 2, 3)   # 3F|B14
ops.element('forceBeamColumn',   167,    67,    65, 2, 3)   # 3F|B23
ops.element('forceBeamColumn',   168,    73,    75, 2, 3)   # 3F|B7
ops.element('forceBeamColumn',   169,    75,    77, 2, 3)   # 3F|B16
ops.element('forceBeamColumn',   170,    77,    79, 2, 3)   # 3F|B24
ops.element('forceBeamColumn',   171,    97,    98, 3, 1)   # 3F|B11
ops.element('forceBeamColumn',   172,    99,   100, 3, 1)   # 3F|B17
ops.element('forceBeamColumn',   173,    83,    82, 3, 2)   # ROOF STAIR|B20
ops.element('forceBeamColumn',   174,    84,    81, 3, 2)   # ROOF STAIR|B10
ops.element('forceBeamColumn',   175,    81,    82, 2, 2)   # ROOF STAIR|B16
ops.element('forceBeamColumn',   176,   101,   102, 2, 1)   # ROOF STAIR|B15
ops.element('forceBeamColumn',   177,   103,   104, 3, 1)   # ROOF STAIR|B11
ops.element('forceBeamColumn',   178,   105,   106, 3, 1)   # ROOF STAIR|B17
ops.element('forceBeamColumn',   179,    84,    83, 2, 2)   # ROOF STAIR|B14
ops.element('forceBeamColumn',   180,   107,   108, 2, 1)   # ROOF DECK|B15
ops.element('forceBeamColumn',   181,   109,   110, 2, 1)   # 2F|B15
ops.element('forceBeamColumn',   182,   111,   112, 2, 1)   # GF|B15
ops.element('forceBeamColumn',   183,   113,   114, 2, 1)   # 3F|B15

# =====================================================================
# SHELL SECTIONS  (ElasticMembranePlateSection, for floor slabs)
# =====================================================================
ops.section('ElasticMembranePlateSection', 5, 21538106, 0.20, 0.1500, 0.0)   # S 150  t=150 mm
ops.section('ElasticMembranePlateSection', 6, 21538106, 0.20, 0.1500, 0.0)   # ST 150 1W  t=150 mm

# =====================================================================
# SHELL ELEMENTS  (ShellMITC4 — one element per rectangular 4-noded panel)
# Non-rectangular or multi-noded panels are listed as comments.
# =====================================================================
ops.element('ShellMITC4',   184,    40,    44,    43,    39, 5)   # 2F|F2
ops.element('ShellMITC4',   185,    46,    43,    44,    45, 5)   # 2F|F3
ops.element('ShellMITC4',   186,   109,   110,    42,    43, 5)   # 2F|F6
ops.element('ShellMITC4',   187,    86,    85,   109,    46, 5)   # 2F|F4
ops.element('ShellMITC4',   188,    87,    88,    47,   110, 5)   # 2F|F8
ops.element('ShellMITC4',   189,    64,    72,    70,    62, 5)   # ROOF DECK|F2
ops.element('ShellMITC4',   190,    76,    70,    72,    74, 5)   # ROOF DECK|F3
ops.element('ShellMITC4',   191,   107,   108,    68,    70, 5)   # ROOF DECK|F6
ops.element('ShellMITC4',   192,    94,    93,   107,    76, 5)   # ROOF DECK|F4
ops.element('ShellMITC4',   193,    95,    96,    78,   108, 5)   # ROOF DECK|F8
ops.element('ShellMITC4',   194,    63,    71,    69,    61, 5)   # 3F|F2
ops.element('ShellMITC4',   195,    75,    69,    71,    73, 5)   # 3F|F3
ops.element('ShellMITC4',   196,   113,   114,    67,    69, 5)   # 3F|F6
ops.element('ShellMITC4',   197,    98,    97,   113,    75, 5)   # 3F|F4
ops.element('ShellMITC4',   198,    99,   100,    77,   114, 5)   # 3F|F8
ops.element('ShellMITC4',   199,    84,    81,    82,    83, 5)   # ROOF STAIR|F7
ops.element('ShellMITC4',   200,    38,    37,    33,    34, 5)   # 2F|F9
ops.element('ShellMITC4',   201,    37,    38,    42,    41, 5)   # 2F|F10
ops.element('ShellMITC4',   202,    41,    42,    47,    48, 5)   # 2F|F11
ops.element('ShellMITC4',   203,    60,    58,    50,    52, 5)   # ROOF DECK|F9
ops.element('ShellMITC4',   204,    58,    60,    68,    66, 5)   # ROOF DECK|F10
ops.element('ShellMITC4',   205,    66,    68,    78,    80, 5)   # ROOF DECK|F11
ops.element('ShellMITC4',   206,    59,    57,    49,    51, 5)   # 3F|F9
ops.element('ShellMITC4',   207,    57,    59,    67,    65, 5)   # 3F|F10
ops.element('ShellMITC4',   208,    65,    67,    77,    79, 5)   # 3F|F11
ops.element('ShellMITC4',   209,    35,    39,    38,    34, 5)   # 2F|F5
ops.element('ShellMITC4',   210,    39,    35,    36,    40, 5)   # 2F|F1
ops.element('ShellMITC4',   211,    54,    62,    60,    52, 5)   # ROOF DECK|F5
ops.element('ShellMITC4',   212,    62,    54,    56,    64, 5)   # ROOF DECK|F1
ops.element('ShellMITC4',   213,    53,    61,    59,    51, 5)   # 3F|F5
ops.element('ShellMITC4',   214,    61,    53,    55,    63, 5)   # 3F|F1
ops.element('ShellMITC4',   215,    85,    86,    88,    87, 6)   # 2F|F12
ops.element('ShellMITC4',   216,    93,    94,    96,    95, 6)   # ROOF DECK|F12
ops.element('ShellMITC4',   217,    97,    98,   100,    99, 6)   # 3F|F12

# =====================================================================
# SECONDARY FRAME COLUMNS  (connect floating GF & Roof-Stair nodes)
# Without these, nodes 89-92/111-112 (z=0) and 101-106 (z=13.8)
# have no path to a fixed support → singular stiffness matrix.
# =====================================================================
# GF (z=0.0) → 2F (z=3.6) secondary frame columns
ops.element('forceBeamColumn',   218,    89,    85, 1, 4)   # GF-2F|SC11
ops.element('forceBeamColumn',   219,    90,    86, 1, 4)   # GF-2F|SC11e
ops.element('forceBeamColumn',   220,    91,    87, 1, 4)   # GF-2F|SC17
ops.element('forceBeamColumn',   221,    92,    88, 1, 4)   # GF-2F|SC17e
ops.element('forceBeamColumn',   222,   111,   109, 1, 4)   # GF-2F|SC15a
ops.element('forceBeamColumn',   223,   112,   110, 1, 4)   # GF-2F|SC15b
# ROOF DECK (z=10.8) → ROOF STAIR (z=13.8) secondary frame columns
ops.element('forceBeamColumn',   224,    93,   103, 1, 4)   # RD-RS|SC11
ops.element('forceBeamColumn',   225,    94,   104, 1, 4)   # RD-RS|SC11e
ops.element('forceBeamColumn',   226,    95,   105, 1, 4)   # RD-RS|SC17
ops.element('forceBeamColumn',   227,    96,   106, 1, 4)   # RD-RS|SC17e
ops.element('forceBeamColumn',   228,   107,   101, 1, 4)   # RD-RS|SC15a
ops.element('forceBeamColumn',   229,   108,   102, 1, 4)   # RD-RS|SC15b

# =====================================================================
# GRAVITY ANALYSIS  (self-weight; add superimposed loads as needed)
# =====================================================================
ops.timeSeries('Linear', 1)
ops.pattern('Plain', 1, 1)

# Y-beams  (geomTransf 2: local_y=+Z)  →  Wy = −w
ops.eleLoad('-ele', 176, 180, 181, 182, 183, '-type', '-beamUniform', -2.4, 0.0, 0.0)
ops.eleLoad('-ele', 124, 125, 126, 136, 137, 138, 139, 140, 141, 142, 143, 144, 175, 179, '-type', '-beamUniform', -3.6, 0.0, 0.0)
ops.eleLoad('-ele', 72, 73, 74, 84, 85, 86, 87, 88, 89, 90, 91, 92, '-type', '-beamUniform', -3.6, 0.0, 0.0)
ops.eleLoad('-ele', 96, 97, 98, 108, 109, 110, 111, 112, 113, 114, 115, 116, 150, 151, 152, 162, 163, 164, 165, 166, 167, 168, 169, 170, '-type', '-beamUniform', -5.04, 0.0, 0.0)
# X-beams  (geomTransf 3: local_y=−Z)  →  Wy = +w
ops.eleLoad('-ele', 117, 118, 119, 120, 145, 146, 171, 172, 177, 178, '-type', '-beamUniform', 2.4, 0.0, 0.0)
ops.eleLoad('-ele', 121, 122, 123, 127, 128, 129, 130, 131, 132, 133, 134, 135, 173, 174, '-type', '-beamUniform', 3.6, 0.0, 0.0)
ops.eleLoad('-ele', 69, 70, 71, 75, 76, 77, 78, 79, 80, 81, 82, 83, 93, 94, 95, 99, 100, 101, 102, 103, 104, 105, 106, 107, 147, 148, 149, 153, 154, 155, 156, 157, 158, 159, 160, 161, '-type', '-beamUniform', 5.04, 0.0, 0.0)
# Columns  (geomTransf 1: local_x=+Z)  →  Wx = −w  (axial)
ops.eleLoad('-ele', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, '-type', '-beamUniform', 0.0, 0.0, -4.86)

ops.system('BandGeneral')
ops.constraints('Transformation')
ops.numberer('RCM')
ops.test('NormDispIncr', 1.0e-12, 10, 3)
ops.algorithm('ModifiedNewton', '-initial')
ops.integrator('LoadControl', 0.1)
ops.analysis('Static')
ops.analyze(10)
print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} gravity analysis complete.')

# Capture total seismic weight W from vertical base reactions after gravity.
# Fixed base nodes: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]
ops.reactions()
_W_seismic = abs(sum(ops.nodeReaction(n, 3)
                     for n in [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]))
print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} total seismic weight W = {_W_seismic:.2f} kN')

# =====================================================================
# MODAL ANALYSIS  —  assign lumped masses from self-weight; ops.eigen(1)
# =====================================================================
# Strategy: for each forceBeamColumn element that carries a distributed
# self-weight load w (kN/m), each end node receives w*L/2 (kN) of
# tributary weight.  ShellMITC4 slabs use rho=0 in their section so they
# contribute no mass.  Fixed base nodes are excluded.
_g_accel = 9.81   # m/s²
_base_nodes_modal = {1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31}

# Element → distributed self-weight intensity |w| (kN/m),
# copied directly from the eleLoad definitions above.
_ele_w_grav = {}
for _et in list(range(1, 69)) + [218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229]:
    _ele_w_grav[_et] = 4.86
for _et in [176, 180, 181, 182, 183]:
    _ele_w_grav[_et] = 2.4
for _et in [72, 73, 74, 84, 85, 86, 87, 88, 89, 90, 91, 92,
            124, 125, 126, 136, 137, 138, 139, 140, 141, 142, 143, 144, 175, 179]:
    _ele_w_grav[_et] = 3.6
for _et in [96, 97, 98, 108, 109, 110, 111, 112, 113, 114, 115, 116,
            150, 151, 152, 162, 163, 164, 165, 166, 167, 168, 169, 170]:
    _ele_w_grav[_et] = 5.04
for _et in [117, 118, 119, 120, 145, 146, 171, 172, 177, 178]:
    _ele_w_grav[_et] = 2.4
for _et in [121, 122, 123, 127, 128, 129, 130, 131, 132, 133, 134, 135, 173, 174]:
    _ele_w_grav[_et] = 3.6
for _et in [69, 70, 71, 75, 76, 77, 78, 79, 80, 81, 82, 83,
            93, 94, 95, 99, 100, 101, 102, 103, 104, 105, 106, 107,
            147, 148, 149, 153, 154, 155, 156, 157, 158, 159, 160, 161]:
    _ele_w_grav[_et] = 5.04

# Accumulate tributary vertical weight (kN) at each non-base node
_node_trib_W = {}
for _et, _w in _ele_w_grav.items():
    _en  = ops.eleNodes(_et)
    _ni, _nj = _en[0], _en[1]
    _ci  = ops.nodeCoord(_ni)
    _cj  = ops.nodeCoord(_nj)
    _L   = math.sqrt(sum((_cj[k] - _ci[k])**2 for k in range(3)))
    for _nd in [_ni, _nj]:
        if _nd not in _base_nodes_modal:
            _node_trib_W[_nd] = _node_trib_W.get(_nd, 0.0) + _w * _L * 0.5

_W_from_masses = sum(_node_trib_W.values())
print(f'Seismic weight check — element loads: {_W_from_masses:.1f} kN | '
      f'base reactions: {_W_seismic:.1f} kN')

# Assign lumped translational masses (kN·s²/m = Mg); no rotational inertia
for _nd, _wt in _node_trib_W.items():
    _m = _wt / _g_accel
    ops.mass(_nd, _m, _m, _m, 0.0, 0.0, 0.0)

# Eigenanalysis — compute 3 modes to identify the current-direction dominant mode.
# In a 3D model with plan asymmetry (roof-stair block), mode 1 (lowest freq)
# may be orthogonal sway or torsion.  We scan all three modes and pick the
# one with the largest effective mass in the requested direction.
ops.wipeAnalysis()
_n_modes = 3
_lambdas  = ops.eigen(_n_modes)

_mi_modal = {nd: _node_trib_W[nd] / _g_accel for nd in _node_trib_W}
_Mt_modal = sum(_mi_modal.values())

print(f'--- Modal scan ({_DIRECTION_LABEL} {_ANALYSIS_LABEL} direction) ---')
_mode_candidates = []
for _m in range(1, _n_modes + 1):
    _om_m = math.sqrt(_lambdas[_m - 1])
    _T_m  = 2.0 * math.pi / _om_m
    # Raw directional DOF components of mode m at every mass-carrying node
    _phi_raw = {nd: ops.nodeEigenvector(nd, _m, _CTRL_DOF) for nd in _mi_modal}
    _phi_max = max(abs(v) for v in _phi_raw.values()) or 1.0
    _phi_n   = {nd: v / _phi_max for nd, v in _phi_raw.items()}
    _Lm = sum(_mi_modal[nd] * _phi_n[nd]    for nd in _mi_modal)
    _Mm = sum(_mi_modal[nd] * _phi_n[nd]**2 for nd in _mi_modal)
    _Meff_dir = (_Lm**2 / _Mm) if _Mm > 1e-12 else 0.0
    print(f'  Mode {_m}: T={_T_m:.3f} s, '
          f'M_eff_{_CURRENT_DIRECTION["axis"]}={_Meff_dir:.2f} Mg '
          f'({100.0 * _Meff_dir / _Mt_modal:.1f}% of total mass)')
    _mode_candidates.append((_Meff_dir, _m, _om_m, _phi_raw, _phi_max))

# Select the mode with the highest directional effective mass
_mode_candidates.sort(key=lambda x: -x[0])
_Meff_dir_best, _mode_dir, _omega1, _phi_raw_best, _phi_max_best = _mode_candidates[0]
_T1 = 2.0 * math.pi / _omega1
print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} dominant mode: '
      f'Mode {_mode_dir}  (T\u2081 = {_T1:.3f} s)')

# Normalise to max|φ|=1 AND enforce POSITIVE sign at the control node.
# OpenSeesPy eigenvector sign is arbitrary; without this fix PF₁ is negative
# whenever the solver returns the mode with all-negative directional components.
_sign_fix = math.copysign(1.0, _phi_raw_best.get(_CTRL_NODE, _phi_max_best))
_phi1_dir = {nd: _sign_fix * v / _phi_max_best for nd, v in _phi_raw_best.items()}

# Modal quantities — directional participation (Chopra §13.1)
#   L₁ = Σ mᵢ φᵢ   (numerator of PF)
#   M₁ = Σ mᵢ φᵢ²  (generalised mass from directional DOF)
#   PF₁ = L₁/M₁,   M*₁ = L₁²/M₁,   α₁ = M*₁/M_total
_Lm_modal = sum(_mi_modal[nd] * _phi1_dir[nd]    for nd in _mi_modal)
_Mm_modal = sum(_mi_modal[nd] * _phi1_dir[nd]**2 for nd in _mi_modal)

_PF1        = _Lm_modal / _Mm_modal
_M_eff1     = _Lm_modal**2 / _Mm_modal
_alpha1     = _M_eff1 / _Mt_modal
_phi_ctrl_1 = _phi1_dir.get(_CTRL_NODE, 1.0)   # ctrl_node = 76 (z = 10.8 m)
_PF1_phi    = _PF1 * _phi_ctrl_1      # always > 0 after sign fix

print(f'PF\u2081 = {_PF1:.4f}  |  \u03c6\u2081(ctrl={_CTRL_NODE}) = {_phi_ctrl_1:.4f}  |  '
      f'PF\u2081\u00b7\u03c6\u2081(ctrl) = {_PF1_phi:.4f}  |  \u03b1\u2081 = {_alpha1:.4f}')

# =====================================================================
# PUSHOVER ANALYSIS  (fill in the TODO items before running)
# =====================================================================
ops.loadConst('-time', 0.0)

# ── lateral load pattern ──────────────────────────────────────────
ops.timeSeries('Linear', 2)
ops.pattern('Plain', 2, 2)
# All nodes at Z = 10.800 m: [50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,93,94,95,96,107,108]
# Distribute reference lateral loads at z=10.8 nodes in the requested direction.
_lateral_load_nodes = [50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
                       72, 74, 76, 78, 80, 93, 94, 95, 96, 107, 108]
for _nd in _lateral_load_nodes:
    _load = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    _load[_CTRL_DOF - 1] = _DIRECTION_SIGN
    ops.load(_nd, *_load)

ops.system('UmfPack')
ops.constraints('Transformation')
ops.numberer('RCM')
ops.test('NormDispIncr', 1.0e-8, 100, 0)
ops.algorithm('Newton')
ops.analysis('Static')

ctrl_node = _CTRL_NODE   # control node at z = 10.800 m
ctrl_dof  = _CTRL_DOF    # 1 = X,  2 = Y,  3 = Z
H_total   = 10.800        # height to control node (m)
target_drift = 0.02       # target drift ratio  (adjust as needed)
target_disp  = target_drift * H_total   # m
n_steps = 200
dU      = _DIRECTION_SIGN * target_disp / n_steps

disp_hist  = [0.0]
shear_hist = [0.0]

ops.integrator("DisplacementControl", ctrl_node, ctrl_dof, dU)

# === PLASTIC HINGE TRACKING SETUP ===
# phi_y = f_y / (E * c)  where c = distance from centroid to extreme bar
# Section 4 [C 450x450]: extreme D16 bar at z = ±0.1770 m from NA
# Section 2 [B 300x500]: extreme D16 bar at z = ±0.1820 m from NA (representative beam)
_fy_steel    = 414.0e3    # kPa
_E_steel     = 210.0e6   # kPa
_phi_y_col_v  = _fy_steel / (_E_steel * 0.1770)   # column φ_y  (rad/m)
_phi_y_beam_v = _fy_steel / (_E_steel * 0.1820)   # beam   φ_y  (rad/m)

# Build node-coord and element-connectivity maps directly from the model
_all_eles_v   = ops.getEleTags()
_elem_nodes_v = {et: tuple(ops.eleNodes(et)[:2]) for et in _all_eles_v}
_all_nodes_v  = ops.getNodeTags()
_node_xyz_v   = {n: tuple(ops.nodeCoord(n)) for n in _all_nodes_v}

# Classify as column when the element axis is predominantly vertical (|Δz| > |Δxy|)
_col_eles_v = set()
for _et, (_ni, _nj) in _elem_nodes_v.items():
    _xi, _yi, _zi = _node_xyz_v[_ni]
    _xj, _yj, _zj = _node_xyz_v[_nj]
    _dz = abs(_zj - _zi)
    _dxy = math.sqrt((_xj - _xi)**2 + (_yj - _yi)**2)
    if _dz > _dxy:
        _col_eles_v.add(_et)

# Element chord lengths for plastic rotation: θ_p = φ_p × w₁ × L  (w₁=0.1 Lobatto)
_elem_lengths_v = {}
for _et, (_ni, _nj) in _elem_nodes_v.items():
    _xi, _yi, _zi = _node_xyz_v[_ni]
    _xj, _yj, _zj = _node_xyz_v[_nj]
    _elem_lengths_v[_et] = math.sqrt((_xj-_xi)**2 + (_yj-_yi)**2 + (_zj-_zi)**2)

# Editable ACI 369.1M-17 acceptance metadata.  The generated model contains
# longitudinal reinforcement explicitly, but not transverse spacing/splice data.
_D16_AREA = 2.010619e-04
_ACI_TRANSVERSE_DEFAULT = 'NC'     # C or NC for ACI 369.1M-17 Table 7 beams
_ACI_COLUMN_RHO_T_DEFAULT = 0.0    # transverse reinforcement ratio for Table 8

_ACI_SECTION_META = {
    1: {
        'kind': 'beam', 'label': 'B250x400', 'b': 0.250, 'h': 0.400,
        'fc_mpa': 21.0, 'fy_mpa': 414.0, 'bar_area': _D16_AREA,
        'top_z': [0.1320, 0.1320],
        'bottom_z': [-0.1320, -0.1320, -0.1320, -0.1320],
        'transverse': _ACI_TRANSVERSE_DEFAULT,
    },
    2: {
        'kind': 'beam', 'label': 'B300x500', 'b': 0.300, 'h': 0.500,
        'fc_mpa': 21.0, 'fy_mpa': 414.0, 'bar_area': _D16_AREA,
        'top_z': [0.1820] * 6,
        'bottom_z': [-0.1820] * 3,
        'transverse': _ACI_TRANSVERSE_DEFAULT,
    },
    3: {
        'kind': 'beam', 'label': 'B350x600', 'b': 0.350, 'h': 0.600,
        'fc_mpa': 21.0, 'fy_mpa': 414.0, 'bar_area': _D16_AREA,
        'top_z': [0.2320] * 9,
        'bottom_z': [-0.2320] * 5,
        'transverse': _ACI_TRANSVERSE_DEFAULT,
    },
    4: {
        'kind': 'column', 'label': 'C450x450', 'b': 0.450, 'h': 0.450,
        'fc_mpa': 28.0, 'fy_mpa': 414.0, 'bar_area': _D16_AREA,
        'bar_count': 42, 'rho_t': _ACI_COLUMN_RHO_T_DEFAULT,
    },
}

_ACI_COLUMN_ELEMS = set(range(1, 69)) | set(range(218, 230))
_ACI_BEAM_SECTION_1_ELEMS = {117, 118, 119, 120, 145, 146, 176, 177,
                             178, 180, 181, 182, 183}
_ACI_BEAM_SECTION_2_ELEMS = (
    {72, 73, 74} | set(range(84, 93)) | set(range(121, 145)) |
    {173, 174, 175, 179}
)
_ACI_BEAM_SECTION_3_ELEMS = (
    {69, 70, 71} | set(range(75, 84)) | set(range(93, 117)) |
    set(range(147, 173))
)

_ACI_ELEMENT_META = {}
for _et in _ACI_COLUMN_ELEMS:
    _ACI_ELEMENT_META[_et] = {'kind': 'column', 'section': 4}
for _et in _ACI_BEAM_SECTION_1_ELEMS:
    _ACI_ELEMENT_META[_et] = {'kind': 'beam', 'section': 1}
for _et in _ACI_BEAM_SECTION_2_ELEMS:
    _ACI_ELEMENT_META[_et] = {'kind': 'beam', 'section': 2}
for _et in _ACI_BEAM_SECTION_3_ELEMS:
    _ACI_ELEMENT_META[_et] = {'kind': 'beam', 'section': 3}

_n_int_pts_v        = 5
_hinge_snapshots_v  = []   # one entry per pushover step
_step_counter_v     = 0

for step in range(n_steps):
    ok = ops.analyze(1)
    if ok != 0:
        ops.algorithm('KrylovNewton')
        ok = ops.analyze(1)
        ops.algorithm('Newton')
    if ok != 0:
        print(f'Analysis stopped at step {step}')
        break
    ops.reactions()
    d = ops.nodeDisp(ctrl_node, ctrl_dof)
    # Sum base reactions in the current pushover direction.
    V = sum(ops.nodeReaction(t, ctrl_dof)
            for t in [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31])
    disp_hist.append(_DIRECTION_SIGN * d * 1000.0)   # positive magnitude [mm]
    shear_hist.append(-_DIRECTION_SIGN * V)          # positive resistive force [kN]

    # --- snapshot every step for animation ---
    _step_counter_v += 1
    _snap_curvs = {}
    _snap_forces = {}
    for _et in _elem_nodes_v:
        _sec_curvs = {}
        for _sn in range(1, _n_int_pts_v + 1):
            try:
                _def = ops.eleResponse(_et, 'section', _sn, 'deformation')
                _sec_curvs[_sn] = math.sqrt(sum(_def[k]**2 for k in range(1, len(_def))))
            except Exception:
                _sec_curvs[_sn] = 0.0
        _snap_curvs[_et] = _sec_curvs
        if _et in _ACI_ELEMENT_META:
            try:
                _snap_forces[_et] = list(ops.eleResponse(_et, 'localForce'))
            except Exception:
                _snap_forces[_et] = []
    _hinge_snapshots_v.append({
        'step': _step_counter_v,
        'disp': _DIRECTION_SIGN * d * 1000.0,
        'shear': -_DIRECTION_SIGN * V,
        'curvatures': _snap_curvs,
        'forces': _snap_forces,
    })

print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} pushover complete.')

# =====================================================================
# VISUALISATION
# =====================================================================
if _SHOW_SINGLE_DIRECTION_DETAIL:
    if opsv is not None:
        opsv.plot_model()

    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(disp_hist, shear_hist, 'r-', linewidth=2, label='OpenSeesPy')
    ax.set_xlabel('Roof displacement  (mm)')
    ax.set_ylabel('Base shear  (kN)')
    ax.set_title(f'{_DIRECTION_LABEL} Pushover Curve')
    ax.axhline(0, color="k", linewidth=0.5)
    ax.axvline(0, color="k", linewidth=0.5)
    ax.legend(); ax.grid(alpha=0.4)
    fig.tight_layout()
    plt.show()

# =====================================================================
# CAPACITY SPECTRUM  (Sa – Sd,  ADRS format)
# =====================================================================
# Conversion from pushover curve to ADRS capacity spectrum (ATC-40 / FEMA 440):
#   Sa [g]  = (V / W) / α₁
#   Sd [m]  = δ_ctrl [m] / (PF₁ × φ₁(ctrl))
# Values of α₁ and PF₁·φ₁(ctrl) are computed from eigenanalysis above.

_Sa_hist = [(v / _W_seismic) / _alpha1  for v in shear_hist]   # [g]
_Sd_hist = [(d / 1000.0)     / _PF1_phi for d in disp_hist ]   # [m]

_SXS = 1.21   # ASCE 41-23 short-period spectral response acceleration [g]
_SX1 = 0.44   # ASCE 41-23 1-second spectral response acceleration [g]
_G   = 9.81   # gravitational acceleration [m/s²]
_TS  = _SX1 / _SXS
_T0  = 0.2 * _TS


def _asce41_23_sa(T):
    """Two-period ASCE 41-23 horizontal spectrum, 5% damping."""
    if T <= 0.0:
        return 0.4 * _SXS
    if T < _T0:
        return _SXS * (0.4 + 0.6 * T / _T0)
    if T <= _TS:
        return _SXS
    return _SX1 / T


def _effective_secant_period(sd, sa):
    """Return T_eff from secant stiffness of the capacity spectrum point."""
    if sd <= 0.0 or sa <= 0.0:
        return None
    omega_sq = (sa * _G) / sd
    if omega_sq <= 0.0:
        return None
    return 2.0 * math.pi / math.sqrt(omega_sq)


def _find_first_intersection(sd_vals, cap_sa_vals, demand_sa_vals, teff_vals):
    """Find the first linearly interpolated cap-demand crossing."""
    if not sd_vals:
        return None

    prev = None
    for sd, cap_sa, demand_sa, teff in zip(sd_vals, cap_sa_vals, demand_sa_vals, teff_vals):
        diff = cap_sa - demand_sa
        point = (sd, cap_sa, demand_sa, teff, diff)
        if abs(diff) <= 1.0e-10:
            return {
                'sd': sd,
                'sa_capacity': cap_sa,
                'sa_demand': demand_sa,
                'sa': cap_sa,
                'teff': teff,
                'is_intersection': True,
            }
        if prev is not None:
            psd, pcap_sa, pdemand_sa, pteff, pdiff = prev
            if pdiff * diff < 0.0:
                ratio = -pdiff / (diff - pdiff)
                sd_pp = psd + ratio * (sd - psd)
                cap_pp = pcap_sa + ratio * (cap_sa - pcap_sa)
                demand_pp = pdemand_sa + ratio * (demand_sa - pdemand_sa)
                teff_pp = pteff + ratio * (teff - pteff)
                return {
                    'sd': sd_pp,
                    'sa_capacity': cap_pp,
                    'sa_demand': demand_pp,
                    'sa': 0.5 * (cap_pp + demand_pp),
                    'teff': teff_pp,
                    'is_intersection': True,
                }
        prev = point

    closest_idx = min(range(len(sd_vals)),
                      key=lambda i: abs(cap_sa_vals[i] - demand_sa_vals[i]))
    return {
        'sd': sd_vals[closest_idx],
        'sa_capacity': cap_sa_vals[closest_idx],
        'sa_demand': demand_sa_vals[closest_idx],
        'sa': cap_sa_vals[closest_idx],
        'teff': teff_vals[closest_idx],
        'is_intersection': False,
    }


def _trapz_area(x_vals, y_vals):
    area = 0.0
    for i in range(1, len(x_vals)):
        dx = x_vals[i] - x_vals[i - 1]
        area += 0.5 * dx * (y_vals[i] + y_vals[i - 1])
    return area


def _fit_initial_stiffness(sd_vals, sa_vals, peak_sa):
    elastic_points = [(sd, sa) for sd, sa in zip(sd_vals, sa_vals)
                      if sd > 0.0 and sa > 0.0 and sa <= 0.60 * peak_sa]
    if len(elastic_points) < 2:
        elastic_points = [(sd, sa) for sd, sa in zip(sd_vals[:5], sa_vals[:5])
                          if sd > 0.0 and sa > 0.0]
    denom = sum(sd * sd for sd, _sa in elastic_points)
    if denom <= 0.0:
        return None
    return sum(sd * sa for sd, sa in elastic_points) / denom


def _idealize_capacity_equal_area(sd_vals, sa_vals):
    """Equal-area bilinear idealization used for HAZUS displacement thresholds."""
    if len(sd_vals) < 2:
        return None

    peak_idx = max(range(len(sa_vals)), key=lambda i: sa_vals[i])
    peak_sa = sa_vals[peak_idx]
    if peak_sa <= 0.0:
        return None

    du_idx = len(sd_vals) - 1
    for i in range(peak_idx + 1, len(sa_vals)):
        if sa_vals[i] <= 0.80 * peak_sa:
            du_idx = i
            break

    du = sd_vals[du_idx]
    au = sa_vals[du_idx]
    if du <= 0.0 or au <= 0.0:
        return None

    k0 = _fit_initial_stiffness(sd_vals[:du_idx + 1], sa_vals[:du_idx + 1], peak_sa)
    if k0 is None or k0 <= 0.0:
        return None

    x_area = [0.0] + sd_vals[:du_idx + 1]
    y_area = [0.0] + sa_vals[:du_idx + 1]
    target_area = _trapz_area(x_area, y_area)

    denom = k0 * du - au
    dy = None
    if abs(denom) > 1.0e-12:
        dy = (2.0 * target_area - du * au) / denom

    dy_upper = min(0.95 * du, sd_vals[peak_idx] if peak_idx <= du_idx else 0.95 * du)
    if dy_upper <= 0.0:
        dy_upper = 0.95 * du
    if dy is None or dy <= 0.0 or dy >= du:
        dy = au / k0
    dy = max(min(dy, dy_upper), 1.0e-9)
    ay = k0 * dy

    thresholds = {
        'Slight': 0.70 * dy,
        'Moderate': dy,
        'Extensive': dy + 0.25 * (du - dy),
        'Complete': du,
    }
    return {
        'Dy': dy,
        'Ay': ay,
        'Du': du,
        'Au': au,
        'initial_stiffness': k0,
        'peak_Sd': sd_vals[peak_idx],
        'peak_Sa': peak_sa,
        'thresholds': thresholds,
    }


def _aci_beta1(fc_mpa):
    if fc_mpa <= 28.0:
        return 0.85
    return max(0.65, 0.85 - 0.05 * (fc_mpa - 28.0) / 7.0)


def _aci_rho_bal(fc_mpa, fy_mpa):
    return 0.85 * _aci_beta1(fc_mpa) * (fc_mpa / fy_mpa) * (600.0 / (600.0 + fy_mpa))


_ACI369_BEAM_TABLE7 = {
    'C': {
        (0.0, 0.25): {'IO': 0.010,  'LS': 0.025, 'CP': 0.050},
        (0.0, 0.50): {'IO': 0.005,  'LS': 0.020, 'CP': 0.040},
        (0.5, 0.25): {'IO': 0.005,  'LS': 0.020, 'CP': 0.030},
        (0.5, 0.50): {'IO': 0.005,  'LS': 0.015, 'CP': 0.020},
    },
    'NC': {
        (0.0, 0.25): {'IO': 0.0050, 'LS': 0.020, 'CP': 0.030},
        (0.0, 0.50): {'IO': 0.0015, 'LS': 0.010, 'CP': 0.015},
        (0.5, 0.25): {'IO': 0.0050, 'LS': 0.010, 'CP': 0.015},
        (0.5, 0.50): {'IO': 0.0015, 'LS': 0.005, 'CP': 0.010},
    },
}


def _clamp(value, lo, hi):
    return max(lo, min(hi, value))


def _interp_aci369_table7(transverse, steel_ratio_index, shear_ratio):
    table = _ACI369_BEAM_TABLE7.get(transverse, _ACI369_BEAM_TABLE7['NC'])
    x = _clamp(steel_ratio_index, 0.0, 0.5)
    y = _clamp(shear_ratio, 0.25, 0.50)
    tx = x / 0.5
    ty = (y - 0.25) / 0.25

    out = {}
    for key in ['IO', 'LS', 'CP']:
        q11 = table[(0.0, 0.25)][key]
        q12 = table[(0.0, 0.50)][key]
        q21 = table[(0.5, 0.25)][key]
        q22 = table[(0.5, 0.50)][key]
        out[key] = ((1.0 - tx) * (1.0 - ty) * q11 +
                    (1.0 - tx) * ty * q12 +
                    tx * (1.0 - ty) * q21 +
                    tx * ty * q22)
    return out


def _local_force_demands(local_force):
    if not local_force:
        return None
    if len(local_force) >= 12:
        axial = max(abs(local_force[0]), abs(local_force[6]))
        shear_i = math.sqrt(local_force[1]**2 + local_force[2]**2)
        shear_j = math.sqrt(local_force[7]**2 + local_force[8]**2)
        return {'axial_kN': axial, 'shear_kN': max(shear_i, shear_j)}
    if len(local_force) >= 6:
        axial = max(abs(local_force[0]), abs(local_force[3]))
        shear = max(abs(local_force[1]), abs(local_force[4]))
        return {'axial_kN': axial, 'shear_kN': shear}
    return None


def _interp_list(a, b, ratio):
    if not a or not b or len(a) != len(b):
        return []
    return [a[i] + ratio * (b[i] - a[i]) for i in range(len(a))]


def _snapshot_bracket_at_disp(snapshots, target_disp_mm):
    if not snapshots:
        return None, None, 0.0
    if target_disp_mm <= snapshots[0]['disp']:
        return snapshots[0], snapshots[0], 0.0
    for i in range(1, len(snapshots)):
        if target_disp_mm <= snapshots[i]['disp']:
            lo = snapshots[i - 1]
            hi = snapshots[i]
            span = hi['disp'] - lo['disp']
            ratio = 0.0 if abs(span) <= 1.0e-12 else (target_disp_mm - lo['disp']) / span
            return lo, hi, _clamp(ratio, 0.0, 1.0)
    return snapshots[-1], snapshots[-1], 0.0


def _interp_member_curvature(lo, hi, ratio, et, sec_num):
    lo_val = lo['curvatures'].get(et, {}).get(sec_num, 0.0)
    hi_val = hi['curvatures'].get(et, {}).get(sec_num, lo_val)
    return lo_val + ratio * (hi_val - lo_val)


def _interp_member_force(lo, hi, ratio, et):
    lo_force = lo.get('forces', {}).get(et, [])
    hi_force = hi.get('forces', {}).get(et, lo_force)
    return _interp_list(lo_force, hi_force, ratio) or lo_force


def _beam_tension_cases(sec):
    fc = sec['fc_mpa']
    fy = sec['fy_mpa']
    rho_bal = _aci_rho_bal(fc, fy)
    b = sec['b']
    h = sec['h']
    area = sec['bar_area']
    top_as = len(sec['top_z']) * area
    bot_as = len(sec['bottom_z']) * area
    z_top = max(sec['top_z'])
    z_bot = min(sec['bottom_z'])
    cases = []
    for name, as_t, as_c, d in [
        ('bottom_tension', bot_as, top_as, h / 2.0 - z_bot),
        ('top_tension', top_as, bot_as, z_top + h / 2.0),
    ]:
        rho = as_t / (b * d)
        rho_prime = as_c / (b * d)
        idx = (rho - rho_prime) / rho_bal if rho_bal > 0.0 else 0.5
        cases.append({
            'name': name,
            'd': d,
            'rho': rho,
            'rho_prime': rho_prime,
            'rho_bal': rho_bal,
            'steel_ratio_index': idx,
        })
    return cases


def _beam_shear_ratio(sec, demand):
    cases = _beam_tension_cases(sec)
    d_eff = max(case['d'] for case in cases)
    denom_kN = (sec['b'] * 1000.0) * (d_eff * 1000.0) * math.sqrt(sec['fc_mpa']) / 1000.0
    if demand is None or denom_kN <= 0.0:
        return 0.50, True
    return demand['shear_kN'] / denom_kN, False


def _aci369_beam_acceptance(sec, local_force):
    demand = _local_force_demands(local_force)
    shear_ratio, warning = _beam_shear_ratio(sec, demand)
    candidates = []
    for case in _beam_tension_cases(sec):
        acc = _interp_aci369_table7(
            sec.get('transverse', _ACI_TRANSVERSE_DEFAULT),
            case['steel_ratio_index'],
            shear_ratio,
        )
        acc.update(case)
        candidates.append(acc)
    controlling = min(candidates, key=lambda item: (item['CP'], item['LS'], item['IO']))
    return {
        'IO': controlling['IO'],
        'LS': controlling['LS'],
        'CP': controlling['CP'],
        'source': 'ACI 369.1M-17 Table 7, flexure-controlled beams',
        'warning': warning,
        'inputs': {
            'transverse': sec.get('transverse', _ACI_TRANSVERSE_DEFAULT),
            'shear_ratio': shear_ratio,
            'tension_case': controlling['name'],
            'rho': controlling['rho'],
            'rho_prime': controlling['rho_prime'],
            'rho_bal': controlling['rho_bal'],
            'steel_ratio_index': controlling['steel_ratio_index'],
        },
    }


def _column_acceptance_from_table8(sec, local_force):
    demand = _local_force_demands(local_force)
    ag = sec['b'] * sec['h']
    rho_l = sec['bar_count'] * sec['bar_area'] / ag
    denom_axial_kN = ag * sec['fc_mpa'] * 1000.0
    denom_shear_kN = (sec['b'] * 1000.0) * (sec['h'] * 1000.0) * math.sqrt(sec['fc_mpa']) / 1000.0
    warning = demand is None
    if demand is None:
        axial_ratio = 0.50
        shear_ratio = 1.00
    else:
        axial_ratio = demand['axial_kN'] / denom_axial_kN if denom_axial_kN > 0.0 else 0.50
        shear_ratio = demand['shear_kN'] / denom_shear_kN if denom_shear_kN > 0.0 else 1.00
    axial_ratio = max(0.10, axial_ratio)
    rho_t = sec.get('rho_t', _ACI_COLUMN_RHO_T_DEFAULT)
    a_nl = max(0.0, 0.042 - 0.043 * axial_ratio + 0.63 * rho_t - 0.023 * shear_ratio)

    def _b_for_axial(ratio):
        denom = 5.0 + (ratio / 0.8) * (1.0 / max(rho_l, 1.0e-6)) * (sec['fc_mpa'] / sec['fy_mpa'])
        return max(0.0, 0.5 / denom - 0.01)

    if axial_ratio <= 0.50:
        b_nl = _b_for_axial(axial_ratio)
    else:
        b_at_05 = _b_for_axial(0.50)
        reduction = _clamp((0.70 - axial_ratio) / 0.20, 0.0, 1.0)
        b_nl = b_at_05 * reduction
    b_nl = max(b_nl, a_nl)

    return {
        'IO': min(0.15 * a_nl, 0.005),
        'LS': 0.50 * b_nl,
        'CP': 0.70 * b_nl,
        'source': 'ACI 369.1M-17 Table 8, columns not controlled by splice/development',
        'warning': warning,
        'inputs': {
            'axial_ratio': axial_ratio,
            'shear_ratio': shear_ratio,
            'rho_l': rho_l,
            'rho_t': rho_t,
            'a_nl': a_nl,
            'b_nl': b_nl,
        },
    }


def _aci369_acceptance(meta, local_force):
    sec = _ACI_SECTION_META[meta['section']]
    if meta['kind'] == 'column':
        return _column_acceptance_from_table8(sec, local_force)
    return _aci369_beam_acceptance(sec, local_force)


def _aci369_damage_category(theta_p, acc):
    if theta_p <= acc['IO']:
        return None
    if theta_p < acc['LS']:
        return 'between IO and LS'
    if theta_p < acc['CP']:
        return 'between LS and CP'
    return '>= CP'


def _member_phi_y(section_id):
    sec = _ACI_SECTION_META[section_id]
    if sec['kind'] == 'column':
        c = 0.1770
    else:
        c = max(abs(z) for z in sec['top_z'] + sec['bottom_z'])
    return (_fy_steel / (_E_steel * c)) if c > 0.0 else 0.0


def _aci369_hinge_counts_at_performance(target_disp_mm):
    counts = {'between IO and LS': 0, 'between LS and CP': 0, '>= CP': 0}
    by_type = {
        'beams': {'between IO and LS': 0, 'between LS and CP': 0, '>= CP': 0},
        'columns': {'between IO and LS': 0, 'between LS and CP': 0, '>= CP': 0},
    }
    members = []
    def _pack_counts():
        for _type_counts in by_type.values():
            _type_counts['total'] = sum(_type_counts[k] for k in counts)
        return {'total': sum(counts.values()), **counts, 'by_type': by_type}

    if target_disp_mm <= 0.0:
        return _pack_counts(), members
    lo, hi, ratio = _snapshot_bracket_at_disp(_hinge_snapshots_v, target_disp_mm)
    if lo is None:
        return _pack_counts(), members

    for et in sorted(_ACI_ELEMENT_META):
        meta = _ACI_ELEMENT_META[et]
        if et not in _elem_nodes_v:
            continue
        L = _elem_lengths_v[et]
        phi_y = _member_phi_y(meta['section'])
        kappa_i = _interp_member_curvature(lo, hi, ratio, et, 1)
        kappa_j = _interp_member_curvature(lo, hi, ratio, et, _n_int_pts_v)
        theta_i = max(0.0, kappa_i - phi_y) * 0.1 * L
        theta_j = max(0.0, kappa_j - phi_y) * 0.1 * L
        theta_p = max(theta_i, theta_j)
        local_force = _interp_member_force(lo, hi, ratio, et)
        acc = _aci369_acceptance(meta, local_force)
        category = _aci369_damage_category(theta_p, acc)
        if category is None:
            continue
        counts[category] += 1
        type_key = 'columns' if meta['kind'] == 'column' else 'beams'
        by_type[type_key][category] += 1
        ni, nj = _elem_nodes_v[et]
        members.append({
            'element': et,
            'kind': meta['kind'],
            'section': meta['section'],
            'section_label': _ACI_SECTION_META[meta['section']]['label'],
            'node_i': ni,
            'node_j': nj,
            'coord_i': list(_node_xyz_v[ni]),
            'coord_j': list(_node_xyz_v[nj]),
            'theta_i': theta_i,
            'theta_j': theta_j,
            'theta_p': theta_p,
            'controlling_end': 'i' if theta_i >= theta_j else 'j',
            'category': category,
            'IO': acc['IO'],
            'LS': acc['LS'],
            'CP': acc['CP'],
            'source': acc['source'],
            'inputs': acc['inputs'],
            'warning': acc['warning'],
        })
    return _pack_counts(), members


def _frame_members_for_hinge_plot():
    members = []
    for et in sorted(_ACI_ELEMENT_META):
        if et not in _elem_nodes_v:
            continue
        ni, nj = _elem_nodes_v[et]
        meta = _ACI_ELEMENT_META[et]
        members.append({
            'element': et,
            'kind': meta['kind'],
            'section': meta['section'],
            'node_i': ni,
            'node_j': nj,
            'coord_i': list(_node_xyz_v[ni]),
            'coord_j': list(_node_xyz_v[nj]),
        })
    return members


_capacity_sd = []
_capacity_sa = []
_demand_sa = []
_teff_hist = []

for _sd, _sa in zip(_Sd_hist, _Sa_hist):
    if _sd <= 0.0 or _sa <= 0.0:
        continue
    if _capacity_sd and _sd <= _capacity_sd[-1] + 1.0e-12:
        continue
    _teff = _effective_secant_period(_sd, _sa)
    if _teff is None:
        continue
    _capacity_sd.append(_sd)
    _capacity_sa.append(_sa)
    _teff_hist.append(_teff)
    _demand_sa.append(_asce41_23_sa(_teff))

_performance_point = _find_first_intersection(
    _capacity_sd, _capacity_sa, _demand_sa, _teff_hist)

if _performance_point is None:
    print('WARNING: No positive capacity-demand points were available.')
else:
    _pp_sd = _performance_point['sd']
    _pp_sa = _performance_point['sa']
    _pp_teff = _performance_point['teff']
    _pp_roof_disp_mm = _pp_sd * _PF1_phi * 1000.0
    _pp_base_shear = _pp_sa * _alpha1 * _W_seismic
    _performance_point['roof_disp_mm'] = _pp_roof_disp_mm
    _performance_point['base_shear_kN'] = _pp_base_shear
    if _performance_point['is_intersection']:
        print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} performance point '
              'from ASCE 41-23 secant-stiffness demand:')
    else:
        print(f'WARNING: No {_DIRECTION_LABEL} {_ANALYSIS_LABEL} '
              'capacity-demand intersection within pushover range; reporting closest approach:')
    print(f'  Sd = {_pp_sd:.5f} m')
    print(f'  Sa = {_pp_sa:.5f} g')
    print(f'  T_eff = {_pp_teff:.4f} s')
    print(f'  Roof displacement = {_pp_roof_disp_mm:.2f} mm')
    print(f'  Base shear = {_pp_base_shear:.2f} kN')
    if not _performance_point['is_intersection']:
        print(f'  Capacity Sa = {_performance_point["sa_capacity"]:.5f} g | '
              f'Demand Sa = {_performance_point["sa_demand"]:.5f} g')

_hazus = _idealize_capacity_equal_area(_capacity_sd, _capacity_sa)
if _hazus is None:
    print(f'WARNING: HAZUS damage thresholds could not be computed for '
          f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL}.')
    _hazus = {
        'Dy': 0.0,
        'Ay': 0.0,
        'Du': max(_capacity_sd or [0.0]),
        'Au': 0.0,
        'initial_stiffness': 0.0,
        'peak_Sd': 0.0,
        'peak_Sa': 0.0,
        'thresholds': {'Slight': 0.0, 'Moderate': 0.0, 'Extensive': 0.0, 'Complete': 0.0},
    }
else:
    print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} HAZUS-MH 2.1 damage thresholds '
          'from equal-area bilinear capacity:')
    print(f'  Dy = {_hazus["Dy"]:.5f} m | Ay = {_hazus["Ay"]:.5f} g')
    print(f'  Du = {_hazus["Du"]:.5f} m | Au = {_hazus["Au"]:.5f} g')
    print('  Thresholds: '
          f'Slight={_hazus["thresholds"]["Slight"]:.5f} m, '
          f'Moderate={_hazus["thresholds"]["Moderate"]:.5f} m, '
          f'Extensive={_hazus["thresholds"]["Extensive"]:.5f} m, '
          f'Complete={_hazus["thresholds"]["Complete"]:.5f} m')

if _performance_point is None and _capacity_sd:
    _idx = min(range(len(_capacity_sd)), key=lambda i: abs(_capacity_sa[i] - _demand_sa[i]))
    _performance_point = {
        'sd': _capacity_sd[_idx],
        'sa_capacity': _capacity_sa[_idx],
        'sa_demand': _demand_sa[_idx],
        'sa': _capacity_sa[_idx],
        'teff': _teff_hist[_idx],
        'is_intersection': False,
    }
    _performance_point['roof_disp_mm'] = _performance_point['sd'] * _PF1_phi * 1000.0
    _performance_point['base_shear_kN'] = _performance_point['sa'] * _alpha1 * _W_seismic
elif _performance_point is None:
    _performance_point = {
        'sd': 0.0,
        'sa_capacity': 0.0,
        'sa_demand': 0.0,
        'sa': 0.0,
        'teff': 0.0,
        'is_intersection': False,
        'roof_disp_mm': 0.0,
        'base_shear_kN': 0.0,
    }

_hinge_damage_counts, _hinging_members = _aci369_hinge_counts_at_performance(
    _performance_point['roof_disp_mm'])
_frame_members = _frame_members_for_hinge_plot()
print(f'{_DIRECTION_LABEL} {_ANALYSIS_LABEL} ACI 369.1M-17 member hinge counts '
      'at performance point:')
print(f'  between IO and LS = {_hinge_damage_counts["between IO and LS"]}')
print(f'  between LS and CP = {_hinge_damage_counts["between LS and CP"]}')
print(f'  >= CP = {_hinge_damage_counts[">= CP"]}')
print(f'  total hinging members = {_hinge_damage_counts["total"]}')
for _member_type in ['beams', 'columns']:
    _type_counts = _hinge_damage_counts['by_type'][_member_type]
    print(f'  {_member_type}: '
          f'IO-LS={_type_counts["between IO and LS"]}, '
          f'LS-CP={_type_counts["between LS and CP"]}, '
          f'>=CP={_type_counts[">= CP"]}, '
          f'total={_type_counts["total"]}')

if os.environ.get(_ADRS_OUTPUT_ENV):
    _worker_payload = {
        'direction': _CURRENT_DIRECTION,
        'modal': {
            'mode': _mode_dir,
            'T1': _T1,
            'alpha1': _alpha1,
            'PF1': _PF1,
            'phi_ctrl': _phi_ctrl_1,
            'PF1_phi': _PF1_phi,
            'effective_mass': _Meff_dir_best,
        },
        'hazard': {
            'SXS': _SXS,
            'SX1': _SX1,
            'TS': _TS,
            'T0': _T0,
        },
        'sd_hist': _Sd_hist,
        'sa_hist': _Sa_hist,
        'capacity_sd': _capacity_sd,
        'capacity_sa': _capacity_sa,
        'demand_sa': _demand_sa,
        'teff': _teff_hist,
        'performance_point': _performance_point,
        'hazus': _hazus,
        'hinge_damage_counts': _hinge_damage_counts,
        'hinging_members': _hinging_members,
        'frame_members': _frame_members,
    }
    with open(os.environ[_ADRS_OUTPUT_ENV], 'w', encoding='utf-8') as _f:
        json.dump(_worker_payload, _f, indent=2)
    sys.exit(0)

fig_cs, ax_cs = plt.subplots(figsize=(7, 5))
ax_cs.plot(_Sd_hist, _Sa_hist, 'b-', linewidth=2, label='Capacity spectrum')
if _capacity_sd:
    ax_cs.plot(_capacity_sd, _demand_sa, 'm--', linewidth=2,
               label='Demand spectrum (ASCE 41-23, secant $T_{eff}$)')
if _performance_point is not None:
    _marker_label = ('Performance point' if _performance_point['is_intersection']
                     else 'Closest approach')
    _marker_color = 'darkgreen' if _performance_point['is_intersection'] else 'dimgray'
    ax_cs.plot(_performance_point['sd'], _performance_point['sa'], 'o',
               color=_marker_color, markersize=7, label=_marker_label)
    ax_cs.annotate(
        f'{_marker_label}\n'
        f'$S_d$={_performance_point["sd"]:.4f} m\n'
        f'$S_a$={_performance_point["sa"]:.3f} g',
        xy=(_performance_point['sd'], _performance_point['sa']),
        xytext=(10, 12),
        textcoords='offset points',
        fontsize=8,
        bbox=dict(boxstyle='round,pad=0.25', fc='white', ec='0.35', alpha=0.9),
        arrowprops=dict(arrowstyle='->', lw=0.8, color='0.35'))
ax_cs.set_xlabel('Spectral displacement  $S_d$  (m)', fontsize=11)
ax_cs.set_ylabel('Spectral acceleration  $S_a$  (g)', fontsize=11)
ax_cs.set_title(
    f'Capacity-Demand Spectrum — E2K Validation Model\n'
    f'$T_1={_T1:.3f}$ s,  '
    f'$\\alpha_1={_alpha1:.3f}$,  '
    f'$PF_1 \\cdot \\phi_1(ctrl)={_PF1_phi:.3f}$,  '
    f'$S_{{XS}}={_SXS:.2f}g$,  $S_{{X1}}={_SX1:.2f}g$',
    fontsize=10)
ax_cs.axhline(0, color='k', linewidth=0.5)
ax_cs.axvline(0, color='k', linewidth=0.5)
ax_cs.legend(fontsize=9)
ax_cs.grid(alpha=0.4)
fig_cs.tight_layout()
plt.show()

# =====================================================================
# PROGRESSIVE PLASTIC HINGE FORMATION  — 3D ISOMETRIC VIEWS
# =====================================================================
def _plot_hinge_frame_3d_v(ax, snap, n_pts):
    """Draw 3D frame with ACI 369.1M-17 hinge damage markers."""
    # structural member lines
    for et, (ni, nj) in _elem_nodes_v.items():
        xi, yi, zi = _node_xyz_v[ni]
        xj, yj, zj = _node_xyz_v[nj]
        ax.plot([xi, xj], [yi, yj], [zi, zj], 'k-', linewidth=1.0, zorder=1)

    # fixed-base markers (nodes at z = −2)
    for bn, (bx, by, bz) in _node_xyz_v.items():
        if bz < -1.5:
            ax.scatter([bx], [by], [bz], marker='^', s=45, c='k', zorder=4)

    # hinge markers at the two end integration points of each element
    _off = 0.08   # fractional offset inward along element axis
    for et, (ni, nj) in _elem_nodes_v.items():
        if et not in _ACI_ELEMENT_META:
            continue
        _meta = _ACI_ELEMENT_META[et]
        _phi_y = _member_phi_y(_meta['section'])
        _acc = _aci369_acceptance(_meta, snap.get('forces', {}).get(et, []))
        L = _elem_lengths_v[et]
        xi, yi, zi = _node_xyz_v[ni]
        xj, yj, zj = _node_xyz_v[nj]
        dx, dy, dz = xj - xi, yj - yi, zj - zi
        for sec_num, is_i_end in [(1, True), (n_pts, False)]:
            kappa   = snap['curvatures'][et][sec_num]
            phi_p   = max(0.0, kappa - _phi_y)
            theta_p = phi_p * 0.1 * L          # plastic rotation (rad)
            _category = _aci369_damage_category(theta_p, _acc)
            if _category is None:
                continue
            if is_i_end:
                hx, hy, hz = xi + _off*dx, yi + _off*dy, zi + _off*dz
            else:
                hx, hy, hz = xj - _off*dx, yj - _off*dy, zj - _off*dz
            color = ('gold' if _category == 'between IO and LS' else
                     'darkorange' if _category == 'between LS and CP' else 'red')
            size  = (55 if _category == 'between IO and LS' else
                     95 if _category == 'between LS and CP' else 135)
            ax.scatter([hx], [hy], [hz], c=color, s=size,
                       edgecolors='black', linewidths=0.6, zorder=5)


if _hinge_snapshots_v:
    _n_frames = len(_hinge_snapshots_v)

    fig_anim = plt.figure(figsize=(8.0, 7.0))
    _ax3d_anim = fig_anim.add_subplot(111, projection='3d')

    _legend_patches = [
        mpatches.Patch(facecolor='gold',       edgecolor='black',
                       label='ACI 369.1M-17: IO < \u03b8\u209a < LS'),
        mpatches.Patch(facecolor='darkorange',  edgecolor='black',
                       label='ACI 369.1M-17: LS \u2264 \u03b8\u209a < CP'),
        mpatches.Patch(facecolor='red',         edgecolor='black',
                       label='ACI 369.1M-17: \u03b8\u209a \u2265 CP'),
    ]
    fig_anim.legend(handles=_legend_patches, loc='lower center', ncol=3,
                    fontsize=8.5, bbox_to_anchor=(0.5, 0.0), framealpha=0.9)

    def _anim_init():
        _ax3d_anim.cla()
        _ax3d_anim.set_xlabel('x (m)', fontsize=7, labelpad=1)
        _ax3d_anim.set_ylabel('y (m)', fontsize=7, labelpad=1)
        _ax3d_anim.set_zlabel('z (m)', fontsize=7, labelpad=1)
        _ax3d_anim.tick_params(labelsize=5)
        _ax3d_anim.set_box_aspect([18.5, 14.0, 16.0])
        _ax3d_anim.view_init(elev=22, azim=-50)
        return []

    def _anim_update(frame_idx):
        snap = _hinge_snapshots_v[frame_idx]
        _ax3d_anim.cla()
        _plot_hinge_frame_3d_v(_ax3d_anim, snap, _n_int_pts_v)
        pct   = (snap['step'] / _n_frames) * 100
        title = (f"Step {snap['step']}/{_n_frames}  ({pct:.0f}% pushover)\n"
                 f"\u0394 = {snap['disp']:.1f} mm     V = {snap['shear']:.1f} kN")
        _ax3d_anim.set_title(title, fontsize=8)
        _ax3d_anim.set_xlabel('x (m)', fontsize=7, labelpad=1)
        _ax3d_anim.set_ylabel('y (m)', fontsize=7, labelpad=1)
        _ax3d_anim.set_zlabel('z (m)', fontsize=7, labelpad=1)
        _ax3d_anim.tick_params(labelsize=5)
        _ax3d_anim.set_box_aspect([18.5, 14.0, 16.0])
        _ax3d_anim.view_init(elev=22, azim=-50)
        fig_anim.suptitle('Progressive Plastic Hinge Formation — E2K Validation Model',
                          fontsize=10, fontweight='bold')
        return []

    _anim = _animation.FuncAnimation(
        fig_anim, _anim_update,
        frames=_n_frames,
        init_func=_anim_init,
        interval=50,       # ms per frame  (50 ms = 20 fps)
        repeat=True,
        blit=False,
    )
    plt.tight_layout(rect=[0, 0.09, 1, 0.96])

    # Save animation — requires ffmpeg (mp4) or pillow (gif)
    _anim_path = 'plastic_hinge_animation.mp4'
    _writer = _animation.FFMpegWriter(fps=20, bitrate=1800)
    print(f'Saving animation to {_anim_path} ...')
    _anim.save(_anim_path, writer=_writer, dpi=150)
    print(f'Animation saved: {_anim_path}')

    plt.show()
